c-------------------------------------------------
c                                                 
c                                                 
c                              -USAGE-            
c                                                 
c     OVERVIEW: call pmf       (xlo,xhi,y,Niny)   
c     computes y(xlo,xhi) by averaging data over  
c     the range [xlo,xhi]. Here x is a scalar, y  
c     a vector, with Niny components used. Piece- 
c     constant Extrapolation is applied to points 
c     laying outside the range of the orig data   
c                                                 
c     domain: x in [ 0.25000E+01, 0.35000E+01]  
c     number of states in vector y:     9         
c     number of x data points:   120              
c                                                 
c     CALLING PROGRAM NEEDS: none                 
c     PROCEDURE NEEDS:  none                      
c     COMPILER NEEDS: f77, long names (14 char)   
c     SYSTEM NEEDS: none                          
c     NOTES: This routine was generated by        
c     subroutine makeRoutine.                     
c                                                 
c-------------------------------------------------
c                                                 
c                          -SPECIFICATION-        
c     SYNTAX:                                     
c     subroutine pmf       (xlo,xhi:dp,y:dp arr, Niny: int)
c     returns: none                               
c     REQUIRES: none                              
c     MODIFIES: y, N                              
c     SIGNALS: none                               
c     EFFECTS: computes the average value of y    
c     over the range [xlo,xhi] and returns number 
c     of components used, N.                      
c                                                 
c-------------------------------------------------
c                                                 
c                         -IMPLEMENTATION-        
c     AUTHOR: auto-generated by makeAveInterp     
c     MODIFICATION HISTORY: none                  
c     NOTES: interpolation x,y data is defined in 
c     data statements for efficiency.             
c     REQUIRES: none                              
c     LOCAL VARIABLES:                            
c     xlo,xhi.........(dp) average y on this range
c     y_vector........(1D dp arr) computed y(x)   
c     Niny............(int) no. of used components
c     x_data..........(dp) x data points          
c     y_data..........(dp) y(x) data points       
c     N...............(int) number of x points    
c     M...............(int) dimension of y_data   
c     i,j,k...........(int) loop index            
c     lo_{lo,hi}side..(int) idx of data near xlo  
c     hi_{lo,hi}side..(int) idx of data near xhi  
c     x1..............(dp) interpolation point    
c     x2..............(dp) interpolation point    
c     y1..............(dp) interpolation value    
c     y2..............(dp) interpolation value    
c     dydx............(dp) slope of linear interp 
c     ylo.............(dp) value at xlo           
c     yhi.............(dp) value at xhi           
c     GLOBAL VARIABLES:none                       
c     PROCEDURES: none                            
c     FILES: none                                 
c     I/O: none                                   
c-------------------------------------------------
c                                                 
c                             -CODE-              
c     FIRST LINE:                                 
      subroutine pmf_H       (xlo,xhi,y_vector,Niny)
c                                                 
c     declare local variables                     
c                                                 
      integer N,M,i,j,k,lo_loside,lo_hiside       
      integer hi_loside,hi_hiside,Niny            
      double precision xlo,xhi,y_vector(*),sum    
      double precision ylo,yhi,x1,y1,x2,y2,dydx   
      double precision x_data(   120)              
      double precision y_data(   120,     9)        
      data N,M /   120,     9/                   
      Niny =      9                                
c                                                 
c     interpolation x,y data                      
c                                                 
      data x_data(     1     ) /   0.250000000000D+01/
      data y_data(     1,   1) /   0.298000000000D+03/
      data y_data(     1,   2) /   0.442539355676D+02/
      data y_data(     1,   3) /   0.113004884040D-02/
      data y_data(     1,   4) /   0.190045214205D+00/
      data y_data(     1,   5) /   0.112391151564D-06/
      data y_data(     1,   6) /   0.950225697307D-01/
      data y_data(     1,   7) /   0.324281491472D-08/
      data y_data(     1,   8) /   0.128564606017D-08/
      data y_data(     1,   9) /   0.714932099145D+00/
      data x_data(     2     ) /   0.266666666667D+01/
      data y_data(     2,   1) /   0.298025612677D+03/
      data y_data(     2,   2) /   0.442577718528D+02/
      data y_data(     2,   3) /   0.112995088722D-02/
      data y_data(     2,   4) /   0.190043965735D+00/
      data y_data(     2,   5) /   0.382122764583D-05/
      data y_data(     2,   6) /   0.950208438563D-01/
      data y_data(     2,   7) /   0.118967570719D-06/
      data y_data(     2,   8) /   0.617324525353D-07/
      data y_data(     2,   9) /   0.714931188481D+00/
      data x_data(     3     ) /   0.275000000000D+01/
      data y_data(     3,   1) /   0.298358527761D+03/
      data y_data(     3,   2) /   0.443076514627D+02/
      data y_data(     3,   3) /   0.112867883809D-02/
      data y_data(     3,   4) /   0.190026479287D+00/
      data y_data(     3,   5) /   0.515426564124D-04/
      data y_data(     3,   6) /   0.949995845796D-01/
      data y_data(     3,   7) /   0.172476435684D-05/
      data y_data(     3,   8) /   0.115714041965D-05/
      data y_data(     3,   9) /   0.714919511572D+00/
      data x_data(     4     ) /   0.283333333333D+01/
      data y_data(     4,   1) /   0.304189668810D+03/
      data y_data(     4,   2) /   0.451816495879D+02/
      data y_data(     4,   3) /   0.110684556734D-02/
      data y_data(     4,   4) /   0.189696827732D+00/
      data y_data(     4,   5) /   0.877573258292D-03/
      data y_data(     4,   6) /   0.946465351829D-01/
      data y_data(     4,   7) /   0.317308648565D-04/
      data y_data(     4,   8) /   0.277535431659D-04/
      data y_data(     4,   9) /   0.714719579419D+00/
      data x_data(     5     ) /   0.283978750000D+01/
      data y_data(     5,   1) /   0.308603017483D+03/
      data y_data(     5,   2) /   0.458433888714D+02/
      data y_data(     5,   3) /   0.109086849385D-02/
      data y_data(     5,   4) /   0.189429232288D+00/
      data y_data(     5,   5) /   0.149359544097D-02/
      data y_data(     5,   6) /   0.943927978109D-01/
      data y_data(     5,   7) /   0.558954666246D-04/
      data y_data(     5,   8) /   0.552613133730D-04/
      data y_data(     5,   9) /   0.714573217680D+00/
      data x_data(     6     ) /   0.284624166667D+01/
      data y_data(     6,   1) /   0.318410786432D+03/
      data y_data(     6,   2) /   0.473144713182D+02/
      data y_data(     6,   3) /   0.105695165090D-02/
      data y_data(     6,   4) /   0.188808052796D+00/
      data y_data(     6,   5) /   0.284422084949D-02/
      data y_data(     6,   6) /   0.938469913934D-01/
      data y_data(     6,   7) /   0.111769411514D-03/
      data y_data(     6,   8) /   0.130209965974D-03/
      data y_data(     6,   9) /   0.714258755583D+00/
      data x_data(     7     ) /   0.284946875000D+01/
      data y_data(     7,   1) /   0.327656613791D+03/
      data y_data(     7,   2) /   0.487017974101D+02/
      data y_data(     7,   3) /   0.102684318097D-02/
      data y_data(     7,   4) /   0.188200269642D+00/
      data y_data(     7,   5) /   0.409746695821D-02/
      data y_data(     7,   6) /   0.933470485647D-01/
      data y_data(     7,   7) /   0.166314117698D-03/
      data y_data(     7,   8) /   0.214549083856D-03/
      data y_data(     7,   9) /   0.713974351633D+00/
      data x_data(     8     ) /   0.285269583333D+01/
      data y_data(     8,   1) /   0.342084267112D+03/
      data y_data(     8,   2) /   0.508676007080D+02/
      data y_data(     8,   3) /   0.983123007086D-03/
      data y_data(     8,   4) /   0.187223914718D+00/
      data y_data(     8,   5) /   0.602128487560D-02/
      data y_data(     8,   6) /   0.925843732273D-01/
      data y_data(     8,   7) /   0.253899382778D-03/
      data y_data(     8,   8) /   0.365982291927D-03/
      data y_data(     8,   9) /   0.713550545505D+00/
      data x_data(     9     ) /   0.285430937500D+01/
      data y_data(     9,   1) /   0.352192566786D+03/
      data y_data(     9,   2) /   0.523856278522D+02/
      data y_data(     9,   3) /   0.954634135767D-03/
      data y_data(     9,   4) /   0.186523635439D+00/
      data y_data(     9,   5) /   0.734726596672D-02/
      data y_data(     9,   6) /   0.920598799833D-01/
      data y_data(     9,   7) /   0.316751454760D-03/
      data y_data(     9,   8) /   0.484965144593D-03/
      data y_data(     9,   9) /   0.713267502011D+00/
      data x_data(    10     ) /   0.285592291667D+01/
      data y_data(    10,   1) /   0.364863975015D+03/
      data y_data(    10,   2) /   0.542892579743D+02/
      data y_data(    10,   3) /   0.921160289112D-03/
      data y_data(    10,   4) /   0.185630467411D+00/
      data y_data(    10,   5) /   0.898662056692D-02/
      data y_data(    10,   6) /   0.914110668054D-01/
      data y_data(    10,   7) /   0.397000917544D-03/
      data y_data(    10,   8) /   0.647243794925D-03/
      data y_data(    10,   9) /   0.712927600504D+00/
      data x_data(    11     ) /   0.285753645833D+01/
      data y_data(    11,   1) /   0.380576423988D+03/
      data y_data(    11,   2) /   0.566507826954D+02/
      data y_data(    11,   3) /   0.882761123358D-03/
      data y_data(    11,   4) /   0.184503767697D+00/
      data y_data(    11,   5) /   0.109882543416D-01/
      data y_data(    11,   6) /   0.906167676641D-01/
      data y_data(    11,   7) /   0.498408749074D-03/
      data y_data(    11,   8) /   0.865791871247D-03/
      data y_data(    11,   9) /   0.712527009677D+00/
      data x_data(    12     ) /   0.285834322917D+01/
      data y_data(    12,   1) /   0.389783664399D+03/
      data y_data(    12,   2) /   0.580350926164D+02/
      data y_data(    12,   3) /   0.861704639671D-03/
      data y_data(    12,   4) /   0.183834599180D+00/
      data y_data(    12,   5) /   0.121458055754D-01/
      data y_data(    12,   6) /   0.901558484879D-01/
      data y_data(    12,   7) /   0.558738452836D-03/
      data y_data(    12,   8) /   0.100236156573D-02/
      data y_data(    12,   9) /   0.712302646738D+00/
      data x_data(    13     ) /   0.285915000000D+01/
      data y_data(    13,   1) /   0.400000000000D+03/
      data y_data(    13,   2) /   0.595715274629D+02/
      data y_data(    13,   3) /   0.839480045269D-03/
      data y_data(    13,   4) /   0.183084942227D+00/
      data y_data(    13,   5) /   0.134178304327D-01/
      data y_data(    13,   6) /   0.896477152610D-01/
      data y_data(    13,   7) /   0.626418634057D-03/
      data y_data(    13,   8) /   0.116086152945D-02/
      data y_data(    13,   9) /   0.712062231916D+00/
      data x_data(    14     ) /   0.286025039063D+01/
      data y_data(    14,   1) /   0.415654985178D+03/
      data y_data(    14,   2) /   0.619267103311D+02/
      data y_data(    14,   3) /   0.807553126977D-03/
      data y_data(    14,   4) /   0.181923287430D+00/
      data y_data(    14,   5) /   0.153443235093D-01/
      data y_data(    14,   6) /   0.888745573559D-01/
      data y_data(    14,   7) /   0.731492888296D-03/
      data y_data(    14,   8) /   0.141647008070D-02/
      data y_data(    14,   9) /   0.711709868736D+00/
      data x_data(    15     ) /   0.286135078125D+01/
      data y_data(    15,   1) /   0.433422075406D+03/
      data y_data(    15,   2) /   0.646008335715D+02/
      data y_data(    15,   3) /   0.774124818621D-03/
      data y_data(    15,   4) /   0.180588055989D+00/
      data y_data(    15,   5) /   0.175006814879D-01/
      data y_data(    15,   6) /   0.880036146128D-01/
      data y_data(    15,   7) /   0.852562475956D-03/
      data y_data(    15,   8) /   0.172343205877D-02/
      data y_data(    15,   9) /   0.711331653376D+00/
      data x_data(    16     ) /   0.286245117188D+01/
      data y_data(    16,   1) /   0.453440452457D+03/
      data y_data(    16,   2) /   0.676152514301D+02/
      data y_data(    16,   3) /   0.739612846415D-03/
      data y_data(    16,   4) /   0.179064183264D+00/
      data y_data(    16,   5) /   0.198958138972D-01/
      data y_data(    16,   6) /   0.870289254273D-01/
      data y_data(    16,   7) /   0.991112745463D-03/
      data y_data(    16,   8) /   0.208895861055D-02/
      data y_data(    16,   9) /   0.710931006055D+00/
      data x_data(    17     ) /   0.286355156250D+01/
      data y_data(    17,   1) /   0.475831337162D+03/
      data y_data(    17,   2) /   0.709886657657D+02/
      data y_data(    17,   3) /   0.704466100776D-03/
      data y_data(    17,   4) /   0.177337347998D+00/
      data y_data(    17,   5) /   0.225359835189D-01/
      data y_data(    17,   6) /   0.859452177183D-01/
      data y_data(    17,   7) /   0.114858159737D-02/
      data y_data(    17,   8) /   0.252053224149D-02/
      data y_data(    17,   9) /   0.710512336926D+00/
      data x_data(    18     ) /   0.286465195313D+01/
      data y_data(    18,   1) /   0.500695621967D+03/
      data y_data(    18,   2) /   0.747367545313D+02/
      data y_data(    18,   3) /   0.669136743827D-03/
      data y_data(    18,   4) /   0.175394199685D+00/
      data y_data(    18,   5) /   0.254247948978D-01/
      data y_data(    18,   6) /   0.847479651260D-01/
      data y_data(    18,   7) /   0.132633654486D-02/
      data y_data(    18,   8) /   0.302580127287D-02/
      data y_data(    18,   9) /   0.710080902474D+00/
      data x_data(    19     ) /   0.286575234375D+01/
      data y_data(    19,   1) /   0.528112846215D+03/
      data y_data(    19,   2) /   0.788719969627D+02/
      data y_data(    19,   3) /   0.634054043224D-03/
      data y_data(    19,   4) /   0.173222515606D+00/
      data y_data(    19,   5) /   0.285633401376D-01/
      data y_data(    19,   6) /   0.834333963288D-01/
      data y_data(    19,   7) /   0.152565730570D-02/
      data y_data(    19,   8) /   0.361248106771D-02/
      data y_data(    19,   9) /   0.709642609554D+00/
      data x_data(    20     ) /   0.286685273438D+01/
      data y_data(    20,   1) /   0.558141486565D+03/
      data y_data(    20,   2) /   0.834036924040D+02/
      data y_data(    20,   3) /   0.599603052693D-03/
      data y_data(    20,   4) /   0.170811286088D+00/
      data y_data(    20,   5) /   0.319504681323D-01/
      data y_data(    20,   6) /   0.819984633649D-01/
      data y_data(    20,   7) /   0.174772444998D-02/
      data y_data(    20,   8) /   0.428826862590D-02/
      data y_data(    20,   9) /   0.709203789339D+00/
      data x_data(    21     ) /   0.286740292969D+01/
      data y_data(    21,   1) /   0.574173407205D+03/
      data y_data(    21,   2) /   0.858240970598D+02/
      data y_data(    21,   3) /   0.582693093019D-03/
      data y_data(    21,   4) /   0.169510445725D+00/
      data y_data(    21,   5) /   0.337383569832D-01/
      data y_data(    21,   6) /   0.812340752361D-01/
      data y_data(    21,   7) /   0.186784340251D-02/
      data y_data(    21,   8) /   0.466302283168D-02/
      data y_data(    21,   9) /   0.708986255822D+00/
      data x_data(    22     ) /   0.286795312500D+01/
      data y_data(    22,   1) /   0.590894259197D+03/
      data y_data(    22,   2) /   0.883491819464D+02/
      data y_data(    22,   3) /   0.566039293965D-03/
      data y_data(    22,   4) /   0.168143760048D+00/
      data y_data(    22,   5) /   0.355889390056D-01/
      data y_data(    22,   6) /   0.804377481544D-01/
      data y_data(    22,   7) /   0.199427025784D-02/
      data y_data(    22,   8) /   0.506408734540D-02/
      data y_data(    22,   9) /   0.708771195188D+00/
      data x_data(    23     ) /   0.286850332031D+01/
      data y_data(    23,   1) /   0.608306155699D+03/
      data y_data(    23,   2) /   0.909793083126D+02/
      data y_data(    23,   3) /   0.549675629534D-03/
      data y_data(    23,   4) /   0.166710125339D+00/
      data y_data(    23,   5) /   0.375015368732D-01/
      data y_data(    23,   6) /   0.796092680901D-01/
      data y_data(    23,   7) /   0.212713051285D-02/
      data y_data(    23,   8) /   0.549247597765D-02/
      data y_data(    23,   9) /   0.708559463207D+00/
      data x_data(    24     ) /   0.286905351563D+01/
      data y_data(    24,   1) /   0.626410167928D+03/
      data y_data(    24,   2) /   0.937146738047D+02/
      data y_data(    24,   3) /   0.533631570607D-03/
      data y_data(    24,   4) /   0.165208521211D+00/
      data y_data(    24,   5) /   0.394753923308D-01/
      data y_data(    24,   6) /   0.787484565710D-01/
      data y_data(    24,   7) /   0.226654212624D-02/
      data y_data(    24,   8) /   0.594918863329D-02/
      data y_data(    24,   9) /   0.708351899128D+00/
      data x_data(    25     ) /   0.286960371094D+01/
      data y_data(    25,   1) /   0.645206439309D+03/
      data y_data(    25,   2) /   0.965553286669D+02/
      data y_data(    25,   3) /   0.517932145867D-03/
      data y_data(    25,   4) /   0.163638001776D+00/
      data y_data(    25,   5) /   0.415096843441D-01/
      data y_data(    25,   6) /   0.778551645882D-01/
      data y_data(    25,   7) /   0.241261626908D-02/
      data y_data(    25,   8) /   0.643521282645D-02/
      data y_data(    25,   9) /   0.708149320196D+00/
      data x_data(    26     ) /   0.287015390625D+01/
      data y_data(    26,   1) /   0.664694276597D+03/
      data y_data(    26,   2) /   0.995011884962D+02/
      data y_data(    26,   3) /   0.502598102868D-03/
      data y_data(    26,   4) /   0.161997698737D+00/
      data y_data(    26,   5) /   0.436035353003D-01/
      data y_data(    26,   6) /   0.769292724372D-01/
      data y_data(    26,   7) /   0.256545693062D-02/
      data y_data(    26,   8) /   0.695152041833D-02/
      data y_data(    26,   9) /   0.707952516177D+00/
      data x_data(    27     ) /   0.287070410156D+01/
      data y_data(    27,   1) /   0.684872264832D+03/
      data y_data(    27,   2) /   0.102552050613D+03/
      data y_data(    27,   3) /   0.487646110171D-03/
      data y_data(    27,   4) /   0.160286810347D+00/
      data y_data(    27,   5) /   0.457560286314D-01/
      data y_data(    27,   6) /   0.759706830563D-01/
      data y_data(    27,   7) /   0.272516190234D-02/
      data y_data(    27,   8) /   0.749907047036D-02/
      data y_data(    27,   9) /   0.707762245593D+00/
      data x_data(    28     ) /   0.287125429688D+01/
      data y_data(    28,   1) /   0.705738346165D+03/
      data y_data(    28,   2) /   0.105707605050D+03/
      data y_data(    28,   3) /   0.473089032220D-03/
      data y_data(    28,   4) /   0.158504606143D+00/
      data y_data(    28,   5) /   0.479662117195D-01/
      data y_data(    28,   6) /   0.749793230000D-01/
      data y_data(    28,   7) /   0.289182222958D-02/
      data y_data(    28,   8) /   0.807880548490D-02/
      data y_data(    28,   9) /   0.707579231423D+00/
      data x_data(    29     ) /   0.287180449219D+01/
      data y_data(    29,   1) /   0.727289927304D+03/
      data y_data(    29,   2) /   0.108967449848D+03/
      data y_data(    29,   3) /   0.458936211145D-03/
      data y_data(    29,   4) /   0.156650413915D+00/
      data y_data(    29,   5) /   0.502331126819D-01/
      data y_data(    29,   6) /   0.739551353139D-01/
      data y_data(    29,   7) /   0.306552339439D-02/
      data y_data(    29,   8) /   0.869165562061D-02/
      data y_data(    29,   9) /   0.707404159074D+00/
      data x_data(    30     ) /   0.287235468750D+01/
      data y_data(    30,   1) /   0.749523938189D+03/
      data y_data(    30,   2) /   0.112331099114D+03/
      data y_data(    30,   3) /   0.445193797316D-03/
      data y_data(    30,   4) /   0.154723626637D+00/
      data y_data(    30,   5) /   0.525557397722D-01/
      data y_data(    30,   6) /   0.728980818507D-01/
      data y_data(    30,   7) /   0.324634452078D-02/
      data y_data(    30,   8) /   0.933853416140D-02/
      data y_data(    30,   9) /   0.707237673058D+00/
      data x_data(    31     ) /   0.287290488281D+01/
      data y_data(    31,   1) /   0.772436925961D+03/
      data y_data(    31,   2) /   0.115797996326D+03/
      data y_data(    31,   3) /   0.431865059481D-03/
      data y_data(    31,   4) /   0.152723687645D+00/
      data y_data(    31,   5) /   0.549330971994D-01/
      data y_data(    31,   6) /   0.718081357686D-01/
      data y_data(    31,   7) /   0.343435967493D-02/
      data y_data(    31,   8) /   0.100203431131D-01/
      data y_data(    31,   9) /   0.707080376599D+00/
      data x_data(    32     ) /   0.287345507813D+01/
      data y_data(    32,   1) /   0.796025087815D+03/
      data y_data(    32,   2) /   0.119367518614D+03/
      data y_data(    32,   3) /   0.418950725893D-03/
      data y_data(    32,   4) /   0.150650100263D+00/
      data y_data(    32,   5) /   0.573641810181D-01/
      data y_data(    32,   6) /   0.706852853615D-01/
      data y_data(    32,   7) /   0.362963666242D-02/
      data y_data(    32,   8) /   0.107379676720D-01/
      data y_data(    32,   9) /   0.706932829023D+00/
      data x_data(    33     ) /   0.287400527344D+01/
      data y_data(    33,   1) /   0.820284346129D+03/
      data y_data(    33,   2) /   0.123038987232D+03/
      data y_data(    33,   3) /   0.406449286492D-03/
      data y_data(    33,   4) /   0.148502411606D+00/
      data y_data(    33,   5) /   0.598479937659D-01/
      data y_data(    33,   6) /   0.695295263704D-01/
      data y_data(    33,   7) /   0.383223822119D-02/
      data y_data(    33,   8) /   0.114922832050D-01/
      data y_data(    33,   9) /   0.706795546831D+00/
      data x_data(    34     ) /   0.287455546875D+01/
      data y_data(    34,   1) /   0.845210349658D+03/
      data y_data(    34,   2) /   0.126811667172D+03/
      data y_data(    34,   3) /   0.394357314958D-03/
      data y_data(    34,   4) /   0.146280225540D+00/
      data y_data(    34,   5) /   0.623835367131D-01/
      data y_data(    34,   6) /   0.683408676080D-01/
      data y_data(    34,   7) /   0.404222004139D-02/
      data y_data(    34,   8) /   0.122841485474D-01/
      data y_data(    34,   9) /   0.706669001550D+00/
      data x_data(    35     ) /   0.287510566406D+01/
      data y_data(    35,   1) /   0.870798521480D+03/
      data y_data(    35,   2) /   0.130684773492D+03/
      data y_data(    35,   3) /   0.382669742122D-03/
      data y_data(    35,   4) /   0.143983186109D+00/
      data y_data(    35,   5) /   0.649698226012D-01/
      data y_data(    35,   6) /   0.671193235979D-01/
      data y_data(    35,   7) /   0.425963127902D-02/
      data y_data(    35,   8) /   0.131144143191D-01/
      data y_data(    35,   9) /   0.706553622094D+00/
      data x_data(    36     ) /   0.287565585938D+01/
      data y_data(    36,   1) /   0.897044018025D+03/
      data y_data(    36,   2) /   0.134657464620D+03/
      data y_data(    36,   3) /   0.371380143777D-03/
      data y_data(    36,   4) /   0.141610995092D+00/
      data y_data(    36,   5) /   0.676058634856D-01/
      data y_data(    36,   6) /   0.658649226570D-01/
      data y_data(    36,   7) /   0.448451095204D-02/
      data y_data(    36,   8) /   0.139839149245D-01/
      data y_data(    36,   9) /   0.706449792888D+00/
      data x_data(    37     ) /   0.287620605469D+01/
      data y_data(    37,   1) /   0.923941732782D+03/
      data y_data(    37,   2) /   0.138728841873D+03/
      data y_data(    37,   3) /   0.360480977827D-03/
      data y_data(    37,   4) /   0.139163397295D+00/
      data y_data(    37,   5) /   0.702906797404D-01/
      data y_data(    37,   6) /   0.645777010645D-01/
      data y_data(    37,   7) /   0.471688650772D-02/
      data y_data(    37,   8) /   0.148934780373D-01/
      data y_data(    37,   9) /   0.706357857355D+00/
      data x_data(    38     ) /   0.287675625000D+01/
      data y_data(    38,   1) /   0.951486191375D+03/
      data y_data(    38,   2) /   0.142897933053D+03/
      data y_data(    38,   3) /   0.349963834346D-03/
      data y_data(    38,   4) /   0.136640205319D+00/
      data y_data(    38,   5) /   0.730232813765D-01/
      data y_data(    38,   6) /   0.632577150709D-01/
      data y_data(    38,   7) /   0.495676687272D-02/
      data y_data(    38,   8) /   0.158439151480D-01/
      data y_data(    38,   9) /   0.706278116213D+00/
      data x_data(    39     ) /   0.287730644531D+01/
      data y_data(    39,   1) /   0.979671477762D+03/
      data y_data(    39,   2) /   0.147163679942D+03/
      data y_data(    39,   3) /   0.339819638860D-03/
      data y_data(    39,   4) /   0.134041291019D+00/
      data y_data(    39,   5) /   0.758026695960D-01/
      data y_data(    39,   6) /   0.619050389636D-01/
      data y_data(    39,   7) /   0.520413668410D-02/
      data y_data(    39,   8) /   0.168360317873D-01/
      data y_data(    39,   9) /   0.706210831950D+00/
      data x_data(    40     ) /   0.287785664063D+01/
      data y_data(    40,   1) /   0.100849102507D+04/
      data y_data(    40,   2) /   0.151524905910D+03/
      data y_data(    40,   3) /   0.330038868996D-03/
      data y_data(    40,   4) /   0.131366622313D+00/
      data y_data(    40,   5) /   0.786278073840D-01/
      data y_data(    40,   6) /   0.605197837356D-01/
      data y_data(    40,   7) /   0.545894302603D-02/
      data y_data(    40,   8) /   0.178706162598D-01/
      data y_data(    40,   9) /   0.706156227281D+00/
      data x_data(    41     ) /   0.287840683594D+01/
      data y_data(    41,   1) /   0.103793717609D+04/
      data y_data(    41,   2) /   0.155980247756D+03/
      data y_data(    41,   3) /   0.320611803678D-03/
      data y_data(    41,   4) /   0.128616267715D+00/
      data y_data(    41,   5) /   0.814976076878D-01/
      data y_data(    41,   6) /   0.591021028564D-01/
      data y_data(    41,   7) /   0.572108160545D-02/
      data y_data(    41,   8) /   0.189484497163D-01/
      data y_data(    41,   9) /   0.706114490419D+00/
      data x_data(    42     ) /   0.287895703125D+01/
      data y_data(    42,   1) /   0.106800058281D+04/
      data y_data(    42,   2) /   0.160528063789D+03/
      data y_data(    42,   3) /   0.311528759464D-03/
      data y_data(    42,   4) /   0.125790451917D+00/
      data y_data(    42,   5) /   0.844108874865D-01/
      data y_data(    42,   6) /   0.576522214402D-01/
      data y_data(    42,   7) /   0.599037312268D-02/
      data y_data(    42,   8) /   0.200702924132D-01/
      data y_data(    42,   9) /   0.706085773621D+00/
      data x_data(    43     ) /   0.287950722656D+01/
      data y_data(    43,   1) /   0.109867044630D+04/
      data y_data(    43,   2) /   0.165166466635D+03/
      data y_data(    43,   3) /   0.302780035137D-03/
      data y_data(    43,   4) /   0.122889583326D+00/
      data y_data(    43,   5) /   0.873663341343D-01/
      data y_data(    43,   6) /   0.561704551078D-01/
      data y_data(    43,   7) /   0.626653686494D-02/
      data y_data(    43,   8) /   0.212368915900D-01/
      data y_data(    43,   9) /   0.706070198977D+00/
      data x_data(    44     ) /   0.288005742188D+01/
      data y_data(    44,   1) /   0.112993394607D+04/
      data y_data(    44,   2) /   0.169893234787D+03/
      data y_data(    44,   3) /   0.294356091541D-03/
      data y_data(    44,   4) /   0.119914338948D+00/
      data y_data(    44,   5) /   0.903624335468D-01/
      data y_data(    44,   6) /   0.546572553910D-01/
      data y_data(    44,   7) /   0.654915259143D-02/
      data y_data(    44,   8) /   0.224489625242D-01/
      data y_data(    44,   9) /   0.706067856999D+00/
      data x_data(    45     ) /   0.288060761719D+01/
      data y_data(    45,   1) /   0.116177558384D+04/
      data y_data(    45,   2) /   0.174705709394D+03/
      data y_data(    45,   3) /   0.286247706183D-03/
      data y_data(    45,   4) /   0.116865725926D+00/
      data y_data(    45,   5) /   0.933974060519D-01/
      data y_data(    45,   6) /   0.531132473603D-01/
      data y_data(    45,   7) /   0.683761829548D-02/
      data y_data(    45,   8) /   0.237071901211D-01/
      data y_data(    45,   9) /   0.706078812245D+00/
      data x_data(    46     ) /   0.288115781250D+01/
      data y_data(    46,   1) /   0.119417630711D+04/
      data y_data(    46,   2) /   0.179600658688D+03/
      data y_data(    46,   3) /   0.278446131193D-03/
      data y_data(    46,   4) /   0.113745201673D+00/
      data y_data(    46,   5) /   0.964691049824D-01/
      data y_data(    46,   6) /   0.515392941667D-01/
      data y_data(    46,   7) /   0.713109697661D-02/
      data y_data(    46,   8) /   0.250122010646D-01/
      data y_data(    46,   9) /   0.706103101137D+00/
      data x_data(    47     ) /   0.288170800781D+01/
      data y_data(    47,   1) /   0.122711252943D+04/
      data y_data(    47,   2) /   0.184574125051D+03/
      data y_data(    47,   3) /   0.270943224342D-03/
      data y_data(    47,   4) /   0.110554774430D+00/
      data y_data(    47,   5) /   0.995749202664D-01/
      data y_data(    47,   6) /   0.499365552891D-01/
      data y_data(    47,   7) /   0.742846088293D-02/
      data y_data(    47,   8) /   0.263645531084D-01/
      data y_data(    47,   9) /   0.706140736023D+00/
      data x_data(    48     ) /   0.288225820313D+01/
      data y_data(    48,   1) /   0.126055495470D+04/
      data y_data(    48,   2) /   0.189621244109D+03/
      data y_data(    48,   3) /   0.263731570829D-03/
      data y_data(    48,   4) /   0.107297156744D+00/
      data y_data(    48,   5) /   0.102711651823D+00/
      data y_data(    48,   6) /   0.483065680486D-01/
      data y_data(    48,   7) /   0.772823063269D-02/
      data y_data(    48,   8) /   0.277646918889D-01/
      data y_data(    48,   9) /   0.706191700862D+00/
      data x_data(    49     ) /   0.288280839844D+01/
      data y_data(    49,   1) /   0.129446733674D+04/
      data y_data(    49,   2) /   0.194736053144D+03/
      data y_data(    49,   3) /   0.256804570925D-03/
      data y_data(    49,   4) /   0.103975898156D+00/
      data y_data(    49,   5) /   0.105875391301D+00/
      data y_data(    49,   6) /   0.466513208326D-01/
      data y_data(    49,   7) /   0.802851891197D-02/
      data y_data(    49,   8) /   0.292129191363D-01/
      data y_data(    49,   9) /   0.706255951661D+00/
      data x_data(    50     ) /   0.288335859375D+01/
      data y_data(    50,   1) /   0.132880514605D+04/
      data y_data(    50,   2) /   0.199911288661D+03/
      data y_data(    50,   3) /   0.250156501447D-03/
      data y_data(    50,   4) /   0.100595553321D+00/
      data y_data(    50,   5) /   0.109061391195D+00/
      data y_data(    50,   6) /   0.449733391605D-01/
      data y_data(    50,   7) /   0.832698234922D-02/
      data y_data(    50,   8) /   0.307093259383D-01/
      data y_data(    50,   9) /   0.706333408036D+00/
      data x_data(    51     ) /   0.288390878906D+01/
      data y_data(    51,   1) /   0.136351429698D+04/
      data y_data(    51,   2) /   0.205138194086D+03/
      data y_data(    51,   3) /   0.243782533010D-03/
      data y_data(    51,   4) /   0.971618196128D-01/
      data y_data(    51,   5) /   0.112263954595D+00/
      data y_data(    51,   6) /   0.432757560714D-01/
      data y_data(    51,   7) /   0.862079173804D-02/
      data y_data(    51,   8) /   0.322537304078D-01/
      data y_data(    51,   9) /   0.706423947575D+00/
      data x_data(    52     ) /   0.288445898438D+01/
      data y_data(    52,   1) /   0.139852998177D+04/
      data y_data(    52,   2) /   0.210406349221D+03/
      data y_data(    52,   3) /   0.237678704832D-03/
      data y_data(    52,   4) /   0.936816789253D-01/
      data y_data(    52,   5) /   0.115476341215D+00/
      data y_data(    52,   6) /   0.415623773705D-01/
      data y_data(    52,   7) /   0.890663020660D-02/
      data y_data(    52,   8) /   0.338455808789D-01/
      data y_data(    52,   9) /   0.706527391404D+00/
      data x_data(    53     ) /   0.288500917969D+01/
      data y_data(    53,   1) /   0.143377577965D+04/
      data y_data(    53,   2) /   0.215703544999D+03/
      data y_data(    53,   3) /   0.231841848365D-03/
      data y_data(    53,   4) /   0.901634903105D-01/
      data y_data(    53,   5) /   0.118690714456D+00/
      data y_data(    53,   6) /   0.398377187758D-01/
      data y_data(    53,   7) /   0.918072709494D-02/
      data y_data(    53,   8) /   0.354838584951D-01/
      data y_data(    53,   9) /   0.706643490867D+00/
      data x_data(    54     ) /   0.288555937500D+01/
      data y_data(    54,   1) /   0.146916314331D+04/
      data y_data(    54,   2) /   0.221015723350D+03/
      data y_data(    54,   3) /   0.226269460893D-03/
      data y_data(    54,   4) /   0.866170463078D-01/
      data y_data(    54,   5) /   0.121898139013D+00/
      data y_data(    54,   6) /   0.381070157921D-01/
      data y_data(    54,   7) /   0.943893880022D-02/
      data y_data(    54,   8) /   0.371669531047D-01/
      data y_data(    54,   9) /   0.706771906982D+00/
      data x_data(    55     ) /   0.288583447266D+01/
      data y_data(    55,   1) /   0.148687212840D+04/
      data y_data(    55,   2) /   0.223671490001D+03/
      data y_data(    55,   3) /   0.223582847197D-03/
      data y_data(    55,   4) /   0.848374291018D-01/
      data y_data(    55,   5) /   0.123495454873D+00/
      data y_data(    55,   6) /   0.372416331126D-01/
      data y_data(    55,   7) /   0.956041012683D-02/
      data y_data(    55,   8) /   0.380244803636D-01/
      data y_data(    55,   9) /   0.706840592422D+00/
      data x_data(    56     ) /   0.288610957031D+01/
      data y_data(    56,   1) /   0.150457763989D+04/
      data y_data(    56,   2) /   0.226324862732D+03/
      data y_data(    56,   3) /   0.220961621130D-03/
      data y_data(    56,   4) /   0.830550501323D-01/
      data y_data(    56,   5) /   0.125087162632D+00/
      data y_data(    56,   6) /   0.363770253416D-01/
      data y_data(    56,   7) /   0.967620091402D-02/
      data y_data(    56,   8) /   0.388923836780D-01/
      data y_data(    56,   9) /   0.706912177302D+00/
      data x_data(    57     ) /   0.288638466797D+01/
      data y_data(    57,   1) /   0.152226519925D+04/
      data y_data(    57,   2) /   0.228973575812D+03/
      data y_data(    57,   3) /   0.218405588478D-03/
      data y_data(    57,   4) /   0.812715310017D-01/
      data y_data(    57,   5) /   0.126671867529D+00/
      data y_data(    57,   6) /   0.355140338383D-01/
      data y_data(    57,   7) /   0.978575015207D-02/
      data y_data(    57,   8) /   0.397702355333D-01/
      data y_data(    57,   9) /   0.706986581946D+00/
      data x_data(    58     ) /   0.288665976563D+01/
      data y_data(    58,   1) /   0.153991969054D+04/
      data y_data(    58,   2) /   0.231615272096D+03/
      data y_data(    58,   3) /   0.215914555714D-03/
      data y_data(    58,   4) /   0.794885664092D-01/
      data y_data(    58,   5) /   0.128248131205D+00/
      data y_data(    58,   6) /   0.346535308454D-01/
      data y_data(    58,   7) /   0.988850651380D-02/
      data y_data(    58,   8) /   0.406575480062D-01/
      data y_data(    58,   9) /   0.707063717021D+00/
      data x_data(    59     ) /   0.288693486328D+01/
      data y_data(    59,   1) /   0.155752542038D+04/
      data y_data(    59,   2) /   0.234247513378D+03/
      data y_data(    59,   3) /   0.213488322032D-03/
      data y_data(    59,   4) /   0.777079170382D-01/
      data y_data(    59,   5) /   0.129814479429D+00/
      data y_data(    59,   6) /   0.337964147428D-01/
      data y_data(    59,   7) /   0.998393595757D-02/
      data y_data(    59,   8) /   0.415537697774D-01/
      data y_data(    59,   9) /   0.707143483055D+00/
      data x_data(    60     ) /   0.288720996094D+01/
      data y_data(    60,   1) /   0.157506618909D+04/
      data y_data(    60,   2) /   0.236867792527D+03/
      data y_data(    60,   3) /   0.211126671287D-03/
      data y_data(    60,   4) /   0.759314005109D-01/
      data y_data(    60,   5) /   0.131369411747D+00/
      data y_data(    60,   6) /   0.329436042882D-01/
      data y_data(    60,   7) /   0.100715297141D-01/
      data y_data(    60,   8) /   0.424582837586D-01/
      data y_data(    60,   9) /   0.707225769981D+00/
      data x_data(    61     ) /   0.288748505859D+01/
      data y_data(    61,   1) /   0.159252537307D+04/
      data y_data(    61,   2) /   0.239473547358D+03/
      data y_data(    61,   3) /   0.208829363924D-03/
      data y_data(    61,   4) /   0.741608817466D-01/
      data y_data(    61,   5) /   0.132911411419D+00/
      data y_data(    61,   6) /   0.320960325425D-01/
      data y_data(    61,   7) /   0.101508125295D-01/
      data y_data(    61,   8) /   0.433704050035D-01/
      data y_data(    61,   9) /   0.707310456758D+00/
      data x_data(    62     ) /   0.288776015625D+01/
      data y_data(    62,   1) /   0.160988601613D+04/
      data y_data(    62,   2) /   0.242062175752D+03/
      data y_data(    62,   3) /   0.206596129345D-03/
      data y_data(    62,   4) /   0.723982617731D-01/
      data y_data(    62,   5) /   0.134438956285D+00/
      data y_data(    62,   6) /   0.312546401978D-01/
      data y_data(    62,   7) /   0.102213504166D-01/
      data y_data(    62,   8) /   0.442893800736D-01/
      data y_data(    62,   9) /   0.707397411254D+00/
      data x_data(    63     ) /   0.288803525391D+01/
      data y_data(    63,   1) /   0.162713093146D+04/
      data y_data(    63,   2) /   0.244631052482D+03/
      data y_data(    63,   3) /   0.204426658284D-03/
      data y_data(    63,   4) /   0.706454657477D-01/
      data y_data(    63,   5) /   0.135950530526D+00/
      data y_data(    63,   6) /   0.304203684102D-01/
      data y_data(    63,   7) /   0.102827588278D-01/
      data y_data(    63,   8) /   0.452143864186D-01/
      data y_data(    63,   9) /   0.707486490070D+00/
      data x_data(    64     ) /   0.288831035156D+01/
      data y_data(    64,   1) /   0.164424280847D+04/
      data y_data(    64,   2) /   0.247177546476D+03/
      data y_data(    64,   3) /   0.202320596204D-03/
      data y_data(    64,   4) /   0.689044304723D-01/
      data y_data(    64,   5) /   0.137444635809D+00/
      data y_data(    64,   6) /   0.295941517821D-01/
      data y_data(    64,   7) /   0.103347092918D-01/
      data y_data(    64,   8) /   0.461445338182D-01/
      data y_data(    64,   9) /   0.707577538827D+00/
      data x_data(    65     ) /   0.288858544922D+01/
      data y_data(    65,   1) /   0.166120432927D+04/
      data y_data(    65,   2) /   0.249699039668D+03/
      data y_data(    65,   3) /   0.200277536661D-03/
      data y_data(    65,   4) /   0.671770905051D-01/
      data y_data(    65,   5) /   0.138919804278D+00/
      data y_data(    65,   6) /   0.287769104666D-01/
      data y_data(    65,   7) /   0.103769367208D-01/
      data y_data(    65,   8) /   0.470788657417D-01/
      data y_data(    65,   9) /   0.707670392287D+00/
      data x_data(    66     ) /   0.288886054688D+01/
      data y_data(    66,   1) /   0.167799828452D+04/
      data y_data(    66,   2) /   0.252192945277D+03/
      data y_data(    66,   3) /   0.198297016264D-03/
      data y_data(    66,   4) /   0.654653654349D-01/
      data y_data(    66,   5) /   0.140374608916D+00/
      data y_data(    66,   6) /   0.279695434639D-01/
      data y_data(    66,   7) /   0.104092440805D-01/
      data y_data(    66,   8) /   0.480163630368D-01/
      data y_data(    66,   9) /   0.707764875068D+00/
      data x_data(    67     ) /   0.288913564453D+01/
      data y_data(    67,   1) /   0.169460769758D+04/
      data y_data(    67,   2) /   0.254656727487D+03/
      data y_data(    67,   3) /   0.196378509474D-03/
      data y_data(    67,   4) /   0.637711447050D-01/
      data y_data(    67,   5) /   0.141807677034D+00/
      data y_data(    67,   6) /   0.271729204468D-01/
      data y_data(    67,   7) /   0.104315080715D-01/
      data y_data(    67,   8) /   0.489559476251D-01/
      data y_data(    67,   9) /   0.707860802118D+00/
      data x_data(    68     ) /   0.288941074219D+01/
      data y_data(    68,   1) /   0.171101594152D+04/
      data y_data(    68,   2) /   0.257087919414D+03/
      data y_data(    68,   3) /   0.194521425532D-03/
      data y_data(    68,   4) /   0.620962758063D-01/
      data y_data(    68,   5) /   0.143217698779D+00/
      data y_data(    68,   6) /   0.263878760424D-01/
      data y_data(    68,   7) /   0.104436811488D-01/
      data y_data(    68,   8) /   0.498964883749D-01/
      data y_data(    68,   9) /   0.707957979848D+00/
      data x_data(    69     ) /   0.288968583984D+01/
      data y_data(    69,   1) /   0.172720686300D+04/
      data y_data(    69,   2) /   0.259484142308D+03/
      data y_data(    69,   3) /   0.192725104997D-03/
      data y_data(    69,   4) /   0.604425485550D-01/
      data y_data(    69,   5) /   0.144603440366D+00/
      data y_data(    69,   6) /   0.256152018528D-01/
      data y_data(    69,   7) /   0.104457949771D-01/
      data y_data(    69,   8) /   0.508368072621D-01/
      data y_data(    69,   9) /   0.708056206987D+00/
      data x_data(    70     ) /   0.288996093750D+01/
      data y_data(    70,   1) /   0.174316489217D+04/
      data y_data(    70,   2) /   0.261843121864D+03/
      data y_data(    70,   3) /   0.190988818860D-03/
      data y_data(    70,   4) /   0.588116853314D-01/
      data y_data(    70,   5) /   0.145963749797D+00/
      data y_data(    70,   6) /   0.248556423213D-01/
      data y_data(    70,   7) /   0.104379594082D-01/
      data y_data(    70,   8) /   0.517756870905D-01/
      data y_data(    70,   9) /   0.708155276051D+00/
      data x_data(    71     ) /   0.289009848633D+01/
      data y_data(    71,   1) /   0.175105062274D+04/
      data y_data(    71,   2) /   0.263007782851D+03/
      data y_data(    71,   3) /   0.190143074966D-03/
      data y_data(    71,   4) /   0.580054738935D-01/
      data y_data(    71,   5) /   0.146633940169D+00/
      data y_data(    71,   6) /   0.244810540201D-01/
      data y_data(    71,   7) /   0.104303762201D-01/
      data y_data(    71,   8) /   0.522441082378D-01/
      data y_data(    71,   9) /   0.708205047459D+00/
      data x_data(    72     ) /   0.289023603516D+01/
      data y_data(    72,   1) /   0.175887237069D+04/
      data y_data(    72,   2) /   0.264162299034D+03/
      data y_data(    72,   3) /   0.189312058360D-03/
      data y_data(    72,   4) /   0.572056121708D-01/
      data y_data(    72,   5) /   0.147297362576D+00/
      data y_data(    72,   6) /   0.241100115380D-01/
      data y_data(    72,   7) /   0.104203731560D-01/
      data y_data(    72,   8) /   0.527116943697D-01/
      data y_data(    72,   9) /   0.708254946190D+00/
      data x_data(    73     ) /   0.289051113281D+01/
      data y_data(    73,   1) /   0.177431946645D+04/
      data y_data(    73,   2) /   0.266440265765D+03/
      data y_data(    73,   3) /   0.187693509566D-03/
      data y_data(    73,   4) /   0.556254469354D-01/
      data y_data(    73,   5) /   0.148603614383D+00/
      data y_data(    73,   6) /   0.233787662980D-01/
      data y_data(    73,   7) /   0.103932237410D-01/
      data y_data(    73,   8) /   0.536439056246D-01/
      data y_data(    73,   9) /   0.708355043018D+00/
      data x_data(    74     ) /   0.289078623047D+01/
      data y_data(    74,   1) /   0.178949154032D+04/
      data y_data(    74,   2) /   0.268674952256D+03/
      data y_data(    74,   3) /   0.186132380973D-03/
      data y_data(    74,   4) /   0.540727814766D-01/
      data y_data(    74,   5) /   0.149881559307D+00/
      data y_data(    74,   6) /   0.226625299037D-01/
      data y_data(    74,   7) /   0.103569138373D-01/
      data y_data(    74,   8) /   0.545708798356D-01/
      data y_data(    74,   9) /   0.708455335639D+00/
      data x_data(    75     ) /   0.289106132813D+01/
      data y_data(    75,   1) /   0.180437638068D+04/
      data y_data(    75,   2) /   0.270864651257D+03/
      data y_data(    75,   3) /   0.184627666767D-03/
      data y_data(    75,   4) /   0.525489524363D-01/
      data y_data(    75,   5) /   0.151130449858D+00/
      data y_data(    75,   6) /   0.219618090382D-01/
      data y_data(    75,   7) /   0.103118474064D-01/
      data y_data(    75,   8) /   0.554913347777D-01/
      data y_data(    75,   9) /   0.708555606483D+00/
      data x_data(    76     ) /   0.289133642578D+01/
      data y_data(    76,   1) /   0.181896281773D+04/
      data y_data(    76,   2) /   0.273007824982D+03/
      data y_data(    76,   3) /   0.183178297452D-03/
      data y_data(    76,   4) /   0.510551792786D-01/
      data y_data(    76,   5) /   0.152349649764D+00/
      data y_data(    76,   6) /   0.212770440577D-01/
      data y_data(    76,   7) /   0.102584899053D-01/
      data y_data(    76,   8) /   0.564039973501D-01/
      data y_data(    76,   9) /   0.708655639644D+00/
      data x_data(    77     ) /   0.289161152344D+01/
      data y_data(    77,   1) /   0.183324078068D+04/
      data y_data(    77,   2) /   0.275103112170D+03/
      data y_data(    77,   3) /   0.181783143698D-03/
      data y_data(    77,   4) /   0.495925587253D-01/
      data y_data(    77,   5) /   0.153538635279D+00/
      data y_data(    77,   6) /   0.206086079247D-01/
      data y_data(    77,   7) /   0.101973614028D-01/
      data y_data(    77,   8) /   0.573076140726D-01/
      data y_data(    77,   9) /   0.708755222595D+00/
      data x_data(    78     ) /   0.289188662109D+01/
      data y_data(    78,   1) /   0.184720134177D+04/
      data y_data(    78,   2) /   0.277149332985D+03/
      data y_data(    78,   3) /   0.180441020848D-03/
      data y_data(    78,   4) /   0.481620607058D-01/
      data y_data(    78,   5) /   0.154696995119D+00/
      data y_data(    78,   6) /   0.199568059934D-01/
      data y_data(    78,   7) /   0.101290289523D-01/
      data y_data(    78,   8) /   0.582009613796D-01/
      data y_data(    78,   9) /   0.708854147850D+00/
      data x_data(    79     ) /   0.289216171875D+01/
      data y_data(    79,   1) /   0.186083674682D+04/
      data y_data(    79,   2) /   0.279145491752D+03/
      data y_data(    79,   3) /   0.179150693989D-03/
      data y_data(    79,   4) /   0.467645258207D-01/
      data y_data(    79,   5) /   0.155824429090D+00/
      data y_data(    79,   6) /   0.193218766031D-01/
      data y_data(    79,   7) /   0.100540984262D-01/
      data y_data(    79,   8) /   0.590828555092D-01/
      data y_data(    79,   9) /   0.708952214551D+00/
      data x_data(    80     ) /   0.289243681641D+01/
      data y_data(    80,   1) /   0.187414043234D+04/
      data y_data(    80,   2) /   0.281090777595D+03/
      data y_data(    80,   3) /   0.177910883449D-03/
      data y_data(    80,   4) /   0.454006642874D-01/
      data y_data(    80,   5) /   0.156920745518D+00/
      data y_data(    80,   6) /   0.187039924204D-01/
      data y_data(    80,   7) /   0.997320602196D-02/
      data y_data(    80,   8) /   0.599521617981D-01/
      data y_data(    80,   9) /   0.709049229954D+00/
      data x_data(    81     ) /   0.289271191406D+01/
      data y_data(    81,   1) /   0.188710702958D+04/
      data y_data(    81,   2) /   0.282984563064D+03/
      data y_data(    81,   3) /   0.176720270639D-03/
      data y_data(    81,   4) /   0.440710563071D-01/
      data y_data(    81,   5) /   0.157985857600D+00/
      data y_data(    81,   6) /   0.181032624580D-01/
      data y_data(    81,   7) /   0.988700964778D-02/
      data y_data(    81,   8) /   0.608078032160D-01/
      data y_data(    81,   9) /   0.709145010771D+00/
      data x_data(    82     ) /   0.289326210938D+01/
      data y_data(    82,   1) /   0.191202225943D+04/
      data y_data(    82,   2) /   0.286617192141D+03/
      data y_data(    82,   3) /   0.174480491549D-03/
      data y_data(    82,   4) /   0.415154701753D-01/
      data y_data(    82,   5) /   0.160022934371D+00/
      data y_data(    82,   6) /   0.169531993429D-01/
      data y_data(    82,   7) /   0.970073086938D-02/
      data y_data(    82,   8) /   0.624752964716D-01/
      data y_data(    82,   9) /   0.709332368770D+00/
      data x_data(    83     ) /   0.289381230469D+01/
      data y_data(    83,   1) /   0.193556317166D+04/
      data y_data(    83,   2) /   0.290042025282D+03/
      data y_data(    83,   3) /   0.172420215735D-03/
      data y_data(    83,   4) /   0.390997047145D-01/
      data y_data(    83,   5) /   0.161937198975D+00/
      data y_data(    83,   6) /   0.158711539992D-01/
      data y_data(    83,   7) /   0.950141292091D-02/
      data y_data(    83,   8) /   0.640775631804D-01/
      data y_data(    83,   9) /   0.709512966210D+00/
      data x_data(    84     ) /   0.289436250000D+01/
      data y_data(    84,   1) /   0.195772778160D+04/
      data y_data(    84,   2) /   0.293260131478D+03/
      data y_data(    84,   3) /   0.170528153006D-03/
      data y_data(    84,   4) /   0.368240089468D-01/
      data y_data(    84,   5) /   0.163731172462D+00/
      data y_data(    84,   6) /   0.148560237436D-01/
      data y_data(    84,   7) /   0.929424561810D-02/
      data y_data(    84,   8) /   0.656087772607D-01/
      data y_data(    84,   9) /   0.709685771968D+00/
      data x_data(    85     ) /   0.289491269531D+01/
      data y_data(    85,   1) /   0.197852987569D+04/
      data y_data(    85,   2) /   0.296274846673D+03/
      data y_data(    85,   3) /   0.168792960769D-03/
      data y_data(    85,   4) /   0.346869745647D-01/
      data y_data(    85,   5) /   0.165408467747D+00/
      data y_data(    85,   6) /   0.139060314783D-01/
      data y_data(    85,   7) /   0.908406385249D-02/
      data y_data(    85,   8) /   0.670644879874D-01/
      data y_data(    85,   9) /   0.709849974370D+00/
      data x_data(    86     ) /   0.289546289063D+01/
      data y_data(    86,   1) /   0.199799701095D+04/
      data y_data(    86,   2) /   0.299091437071D+03/
      data y_data(    86,   3) /   0.167203411308D-03/
      data y_data(    86,   4) /   0.326857618561D-01/
      data y_data(    86,   5) /   0.166973562424D+00/
      data y_data(    86,   6) /   0.130188610138D-01/
      data y_data(    86,   7) /   0.887519906886D-02/
      data y_data(    86,   8) /   0.684416335653D-01/
      data y_data(    86,   9) /   0.710004982072D+00/
      data x_data(    87     ) /   0.289601308594D+01/
      data y_data(    87,   1) /   0.201616830631D+04/
      data y_data(    87,   2) /   0.301716743409D+03/
      data y_data(    87,   3) /   0.165748536214D-03/
      data y_data(    87,   4) /   0.308163423825D-01/
      data y_data(    87,   5) /   0.168431578511D+00/
      data y_data(    87,   6) /   0.121917888350D-01/
      data y_data(    87,   7) /   0.867138246233D-02/
      data y_data(    87,   8) /   0.697384926080D-01/
      data y_data(    87,   9) /   0.710150415201D+00/
      data x_data(    88     ) /   0.289656328125D+01/
      data y_data(    88,   1) /   0.203309217030D+04/
      data y_data(    88,   2) /   0.304158827490D+03/
      data y_data(    88,   3) /   0.164417745110D-03/
      data y_data(    88,   4) /   0.290737434624D-01/
      data y_data(    88,   5) /   0.169788079130D+00/
      data y_data(    88,   6) /   0.114218061047D-01/
      data y_data(    88,   7) /   0.847569687190D-02/
      data y_data(    88,   8) /   0.709545855941D-01/
      data y_data(    88,   9) /   0.710286088837D+00/
      data x_data(    89     ) /   0.289711347656D+01/
      data y_data(    89,   1) /   0.204882408508D+04/
      data y_data(    89,   2) /   0.306426637666D+03/
      data y_data(    89,   3) /   0.163200918015D-03/
      data y_data(    89,   4) /   0.274522825198D-01/
      data y_data(    89,   5) /   0.171048888598D+00/
      data y_data(    89,   6) /   0.107057268766D-01/
      data y_data(    89,   7) /   0.829057069670D-02/
      data y_data(    89,   8) /   0.720905401708D-01/
      data y_data(    89,   9) /   0.710411991138D+00/
      data x_data(    90     ) /   0.289766367188D+01/
      data y_data(    90,   1) /   0.206342453811D+04/
      data y_data(    90,   2) /   0.308529705020D+03/
      data y_data(    90,   3) /   0.162088472382D-03/
      data y_data(    90,   4) /   0.259457826162D-01/
      data y_data(    90,   5) /   0.172219939263D+00/
      data y_data(    90,   6) /   0.100402804247D-01/
      data y_data(    90,   7) /   0.811780515387D-02/
      data y_data(    90,   8) /   0.731479341981D-01/
      data y_data(    90,   9) /   0.710528258344D+00/
      data x_data(    91     ) /   0.289821386719D+01/
      data y_data(    91,   1) /   0.207695716362D+04/
      data y_data(    91,   2) /   0.310477877393D+03/
      data y_data(    91,   3) /   0.161071407056D-03/
      data y_data(    91,   4) /   0.245477635994D-01/
      data y_data(    91,   5) /   0.173307145877D+00/
      data y_data(    91,   6) /   0.942218716046D-02/
      data y_data(    91,   7) /   0.795862561530D-02/
      data y_data(    91,   8) /   0.741291291389D-01/
      data y_data(    91,   9) /   0.710635148609D+00/
      data x_data(    92     ) /   0.289848896484D+01/
      data y_data(    92,   1) /   0.208334649458D+04/
      data y_data(    92,   2) /   0.311397447807D+03/
      data y_data(    92,   3) /   0.160595756078D-03/
      data y_data(    92,   4) /   0.238870322719D-01/
      data y_data(    92,   5) /   0.173821417493D+00/
      data y_data(    92,   6) /   0.912971921714D-02/
      data y_data(    92,   7) /   0.788440877807D-02/
      data y_data(    92,   8) /   0.745922195438D-01/
      data y_data(    92,   9) /   0.710685202696D+00/
      data x_data(    93     ) /   0.289876406250D+01/
      data y_data(    93,   1) /   0.208949162919D+04/
      data y_data(    93,   2) /   0.312281781043D+03/
      data y_data(    93,   3) /   0.160140973977D-03/
      data y_data(    93,   4) /   0.232511221315D-01/
      data y_data(    93,   5) /   0.174316782596D+00/
      data y_data(    93,   6) /   0.884796015665D-02/
      data y_data(    93,   7) /   0.781384333443D-02/
      data y_data(    93,   8) /   0.750372512958D-01/
      data y_data(    93,   9) /   0.710733040486D+00/
      data x_data(    94     ) /   0.289931425781D+01/
      data y_data(    94,   1) /   0.210107558720D+04/
      data y_data(    94,   2) /   0.313948702799D+03/
      data y_data(    94,   3) /   0.159290699803D-03/
      data y_data(    94,   4) /   0.220511367236D-01/
      data y_data(    94,   5) /   0.175252995585D+00/
      data y_data(    94,   6) /   0.831534431286D-02/
      data y_data(    94,   7) /   0.768372131492D-02/
      data y_data(    94,   8) /   0.758745540129D-01/
      data y_data(    94,   9) /   0.710822248051D+00/
      data x_data(    95     ) /   0.289986445313D+01/
      data y_data(    95,   1) /   0.211178642524D+04/
      data y_data(    95,   2) /   0.315490100322D+03/
      data y_data(    95,   3) /   0.158512449425D-03/
      data y_data(    95,   4) /   0.209399008400D-01/
      data y_data(    95,   5) /   0.176122121312D+00/
      data y_data(    95,   6) /   0.782072883863D-02/
      data y_data(    95,   7) /   0.756811756532D-02/
      data y_data(    95,   8) /   0.766457949500D-01/
      data y_data(    95,   9) /   0.710903336494D+00/
      data x_data(    96     ) /   0.290041464844D+01/
      data y_data(    96,   1) /   0.212168669891D+04/
      data y_data(    96,   2) /   0.316915225537D+03/
      data y_data(    96,   3) /   0.157799640224D-03/
      data y_data(    96,   4) /   0.199110977986D-01/
      data y_data(    96,   5) /   0.176929233487D+00/
      data y_data(    96,   6) /   0.736126788896D-02/
      data y_data(    96,   7) /   0.746667382133D-02/
      data y_data(    96,   8) /   0.773549140565D-01/
      data y_data(    96,   9) /   0.710976812947D+00/
      data x_data(    97     ) /   0.290096484375D+01/
      data y_data(    97,   1) /   0.213083653112D+04/
      data y_data(    97,   2) /   0.318232904508D+03/
      data y_data(    97,   3) /   0.157146253146D-03/
      data y_data(    97,   4) /   0.189586649545D-01/
      data y_data(    97,   5) /   0.177679102600D+00/
      data y_data(    97,   6) /   0.693428177834D-02/
      data y_data(    97,   7) /   0.737881484537D-02/
      data y_data(    97,   8) /   0.780059360300D-01/
      data y_data(    97,   9) /   0.711043199792D+00/
      data x_data(    98     ) /   0.290151503906D+01/
      data y_data(    98,   1) /   0.213929315639D+04/
      data y_data(    98,   2) /   0.319451485360D+03/
      data y_data(    98,   3) /   0.156546802451D-03/
      data y_data(    98,   4) /   0.180768372611D-01/
      data y_data(    98,   5) /   0.178376186316D+00/
      data y_data(    98,   6) /   0.653726360379D-02/
      data y_data(    98,   7) /   0.730380817103D-02/
      data y_data(    98,   8) /   0.786028830136D-01/
      data y_data(    98,   9) /   0.711103021634D+00/
      data x_data(    99     ) /   0.290206523438D+01/
      data y_data(    99,   1) /   0.214711062409D+04/
      data y_data(    99,   2) /   0.320578807865D+03/
      data y_data(    99,   3) /   0.155996302139D-03/
      data y_data(    99,   4) /   0.172601750165D-01/
      data y_data(    99,   5) /   0.179024628852D+00/
      data y_data(    99,   6) /   0.616788050622D-02/
      data y_data(    99,   7) /   0.724081537805D-02/
      data y_data(    99,   8) /   0.791497052288D-01/
      data y_data(    99,   9) /   0.711156795019D+00/
      data x_data(   100     ) /   0.290261542969D+01/
      data y_data(   100,   1) /   0.215433963234D+04/
      data y_data(   100,   2) /   0.321622190418D+03/
      data y_data(   100,   3) /   0.155490230654D-03/
      data y_data(   100,   4) /   0.165035787331D-01/
      data y_data(   100,   5) /   0.179628267037D+00/
      data y_data(   100,   6) /   0.582397093083D-02/
      data y_data(   100,   7) /   0.718893482234D-02/
      data y_data(   100,   8) /   0.796502278888D-01/
      data y_data(   100,   9) /   0.711205020588D+00/
      data x_data(   101     ) /   0.290316562500D+01/
      data y_data(   101,   1) /   0.216102746634D+04/
      data y_data(   101,   2) /   0.322588430527D+03/
      data y_data(   101,   3) /   0.155024495112D-03/
      data y_data(   101,   4) /   0.158022938018D-01/
      data y_data(   101,   5) /   0.180190641167D+00/
      data y_data(   101,   6) /   0.550353901700D-02/
      data y_data(   101,   7) /   0.714723624393D-02/
      data y_data(   101,   8) /   0.801081123894D-01/
      data y_data(   101,   9) /   0.711248177380D+00/
      data x_data(   102     ) /   0.290426601563D+01/
      data y_data(   102,   1) /   0.217291484834D+04/
      data y_data(   102,   2) /   0.324308916732D+03/
      data y_data(   102,   3) /   0.154202077067D-03/
      data y_data(   102,   4) /   0.145521247043D-01/
      data y_data(   102,   5) /   0.181201609288D+00/
      data y_data(   102,   6) /   0.492747730005D-02/
      data y_data(   102,   7) /   0.709155770310D-02/
      data y_data(   102,   8) /   0.809065597249D-01/
      data y_data(   102,   9) /   0.711320671280D+00/
      data x_data(   103     ) /   0.290536640625D+01/
      data y_data(   103,   1) /   0.218314609920D+04/
      data y_data(   103,   2) /   0.325793332423D+03/
      data y_data(   103,   3) /   0.153499484472D-03/
      data y_data(   103,   4) /   0.134718550803D-01/
      data y_data(   103,   5) /   0.182084765585D+00/
      data y_data(   103,   6) /   0.442409882369D-02/
      data y_data(   103,   7) /   0.706541660081D-02/
      data y_data(   103,   8) /   0.815757698408D-01/
      data y_data(   103,   9) /   0.711378094070D+00/
      data x_data(   104     ) /   0.290646679688D+01/
      data y_data(   104,   1) /   0.219198111301D+04/
      data y_data(   104,   2) /   0.327078615214D+03/
      data y_data(   104,   3) /   0.152896295401D-03/
      data y_data(   104,   4) /   0.125353210767D-01/
      data y_data(   104,   5) /   0.182859149732D+00/
      data y_data(   104,   6) /   0.398265683625D-02/
      data y_data(   104,   7) /   0.706252846034D-02/
      data y_data(   104,   8) /   0.821371283038D-01/
      data y_data(   104,   9) /   0.711423215591D+00/
      data x_data(   105     ) /   0.290756718750D+01/
      data y_data(   105,   1) /   0.219963833588D+04/
      data y_data(   105,   2) /   0.328195721072D+03/
      data y_data(   105,   3) /   0.152375870130D-03/
      data y_data(   105,   4) /   0.117204976302D-01/
      data y_data(   105,   5) /   0.183540721249D+00/
      data y_data(   105,   6) /   0.359413402157D-02/
      data y_data(   105,   7) /   0.707743839013D-02/
      data y_data(   105,   8) /   0.826088358354D-01/
      data y_data(   105,   9) /   0.711458372874D+00/
      data x_data(   106     ) /   0.290866757813D+01/
      data y_data(   106,   1) /   0.220630058423D+04/
      data y_data(   106,   2) /   0.329170508661D+03/
      data y_data(   106,   3) /   0.151924632540D-03/
      data y_data(   106,   4) /   0.110089158764D-01/
      data y_data(   106,   5) /   0.184142849211D+00/
      data y_data(   106,   6) /   0.325096935031D-02/
      data y_data(   106,   7) /   0.710554058793D-02/
      data y_data(   106,   8) /   0.830062131270D-01/
      data y_data(   106,   9) /   0.711485511847D+00/
      data x_data(   107     ) /   0.290976796875D+01/
      data y_data(   107,   1) /   0.221212063267D+04/
      data y_data(   107,   2) /   0.330024563221D+03/
      data y_data(   107,   3) /   0.151531474152D-03/
      data y_data(   107,   4) /   0.103851082188D-01/
      data y_data(   107,   5) /   0.184676743050D+00/
      data y_data(   107,   6) /   0.294681745237D-02/
      data y_data(   107,   7) /   0.714300929046D-02/
      data y_data(   107,   8) /   0.833420821125D-01/
      data y_data(   107,   9) /   0.711506239875D+00/
      data x_data(   108     ) /   0.291196875000D+01/
      data y_data(   108,   1) /   0.222162173156D+04/
      data y_data(   108,   2) /   0.331425261758D+03/
      data y_data(   108,   3) /   0.150891058533D-03/
      data y_data(   108,   4) /   0.936155023243D-02/
      data y_data(   108,   5) /   0.185568388420D+00/
      data y_data(   108,   6) /   0.243939495242D-02/
      data y_data(   108,   7) /   0.723655444060D-02/
      data y_data(   108,   8) /   0.838616612467D-01/
      data y_data(   108,   9) /   0.711532450708D+00/
      data x_data(   109     ) /   0.291637031250D+01/
      data y_data(   109,   1) /   0.223454334074D+04/
      data y_data(   109,   2) /   0.333346727718D+03/
      data y_data(   109,   3) /   0.150021297385D-03/
      data y_data(   109,   4) /   0.795644416126D-02/
      data y_data(   109,   5) /   0.186831794144D+00/
      data y_data(   109,   6) /   0.172172287226D-02/
      data y_data(   109,   7) /   0.744605829551D-02/
      data y_data(   109,   8) /   0.844963637536D-01/
      data y_data(   109,   9) /   0.711547616774D+00/
      data x_data(   110     ) /   0.292077187500D+01/
      data y_data(   110,   1) /   0.224298230437D+04/
      data y_data(   110,   2) /   0.334612777689D+03/
      data y_data(   110,   3) /   0.149453672740D-03/
      data y_data(   110,   4) /   0.702941872541D-02/
      data y_data(   110,   5) /   0.187690901980D+00/
      data y_data(   110,   6) /   0.123402140898D-02/
      data y_data(   110,   7) /   0.763994961882D-02/
      data y_data(   110,   8) /   0.848626949028D-01/
      data y_data(   110,   9) /   0.711543013364D+00/
      data x_data(   111     ) /   0.292517343750D+01/
      data y_data(   111,   1) /   0.224872426489D+04/
      data y_data(   111,   2) /   0.335480950961D+03/
      data y_data(   111,   3) /   0.149066909546D-03/
      data y_data(   111,   4) /   0.639356956982D-02/
      data y_data(   111,   5) /   0.188295956534D+00/
      data y_data(   111,   6) /   0.891171637154D-03/
      data y_data(   111,   7) /   0.780480971062D-02/
      data y_data(   111,   8) /   0.850834161636D-01/
      data y_data(   111,   9) /   0.711531076385D+00/
      data x_data(   112     ) /   0.292957500000D+01/
      data y_data(   112,   1) /   0.225280215005D+04/
      data y_data(   112,   2) /   0.336101414589D+03/
      data y_data(   112,   3) /   0.148791722976D-03/
      data y_data(   112,   4) /   0.593940332479D-02/
      data y_data(   112,   5) /   0.188737612420D+00/
      data y_data(   112,   6) /   0.641580971973D-03/
      data y_data(   112,   7) /   0.793994899772D-02/
      data y_data(   112,   8) /   0.852239809797D-01/
      data y_data(   112,   9) /   0.711517473306D+00/
      data x_data(   113     ) /   0.294718125000D+01/
      data y_data(   113,   1) /   0.225915969723D+04/
      data y_data(   113,   2) /   0.337079264933D+03/
      data y_data(   113,   3) /   0.148360085517D-03/
      data y_data(   113,   4) /   0.522677566190D-02/
      data y_data(   113,   5) /   0.189462551671D+00/
      data y_data(   113,   6) /   0.236910377051D-03/
      data y_data(   113,   7) /   0.819387180280D-02/
      data y_data(   113,   8) /   0.854021251364D-01/
      data y_data(   113,   9) /   0.711477765351D+00/
      data x_data(   114     ) /   0.296478750000D+01/
      data y_data(   114,   1) /   0.226146539157D+04/
      data y_data(   114,   2) /   0.337436732208D+03/
      data y_data(   114,   3) /   0.148202918645D-03/
      data y_data(   114,   4) /   0.496659509305D-02/
      data y_data(   114,   5) /   0.189734993169D+00/
      data y_data(   114,   6) /   0.856355204228D-04/
      data y_data(   114,   7) /   0.829888354863D-02/
      data y_data(   114,   8) /   0.854555402529D-01/
      data y_data(   114,   9) /   0.711458352416D+00/
      data x_data(   115     ) /   0.300000000000D+01/
      data y_data(   115,   1) /   0.226248580617D+04/
      data y_data(   115,   2) /   0.337595743628D+03/
      data y_data(   115,   3) /   0.148133113391D-03/
      data y_data(   115,   4) /   0.485135422218D-02/
      data y_data(   115,   5) /   0.189858884695D+00/
      data y_data(   115,   6) /   0.175977950542D-04/
      data y_data(   115,   7) /   0.834803062101D-02/
      data y_data(   115,   8) /   0.854763862227D-01/
      data y_data(   115,   9) /   0.711447746444D+00/
      data x_data(   116     ) /   0.304166666667D+01/
      data y_data(   116,   1) /   0.226270185028D+04/
      data y_data(   116,   2) /   0.337629469618D+03/
      data y_data(   116,   3) /   0.148118316295D-03/
      data y_data(   116,   4) /   0.482693812798D-02/
      data y_data(   116,   5) /   0.189885355897D+00/
      data y_data(   116,   6) /   0.310621534966D-05/
      data y_data(   116,   7) /   0.835865854170D-02/
      data y_data(   116,   8) /   0.854805894472D-01/
      data y_data(   116,   9) /   0.711445351770D+00/
      data x_data(   117     ) /   0.308333333333D+01/
      data y_data(   117,   1) /   0.226274039320D+04/
      data y_data(   117,   2) /   0.337635497575D+03/
      data y_data(   117,   3) /   0.148115671872D-03/
      data y_data(   117,   4) /   0.482259420149D-02/
      data y_data(   117,   5) /   0.189890143605D+00/
      data y_data(   117,   6) /   0.513336891251D-06/
      data y_data(   117,   7) /   0.836055575948D-02/
      data y_data(   117,   8) /   0.854813148593D-01/
      data y_data(   117,   9) /   0.711444878238D+00/
      data x_data(   118     ) /   0.316666666667D+01/
      data y_data(   118,   1) /   0.226274738510D+04/
      data y_data(   118,   2) /   0.337636593946D+03/
      data y_data(   118,   3) /   0.148115190912D-03/
      data y_data(   118,   4) /   0.482180996919D-02/
      data y_data(   118,   5) /   0.189891030622D+00/
      data y_data(   118,   6) /   0.415105942204D-07/
      data y_data(   118,   7) /   0.836089771230D-02/
      data y_data(   118,   8) /   0.854814413839D-01/
      data y_data(   118,   9) /   0.711444778802D+00/
      data x_data(   119     ) /   0.333333333333D+01/
      data y_data(   119,   1) /   0.226274797101D+04/
      data y_data(   119,   2) /   0.337636685915D+03/
      data y_data(   119,   3) /   0.148115150567D-03/
      data y_data(   119,   4) /   0.482174393880D-02/
      data y_data(   119,   5) /   0.189891105857D+00/
      data y_data(   119,   6) /   0.169831629724D-08/
      data y_data(   119,   7) /   0.836092647691D-02/
      data y_data(   119,   8) /   0.854814519436D-01/
      data y_data(   119,   9) /   0.711444770086D+00/
      data x_data(   120     ) /   0.350000000000D+01/
      data y_data(   120,   1) /   0.226274797101D+04/
      data y_data(   120,   2) /   0.337636685915D+03/
      data y_data(   120,   3) /   0.148115150567D-03/
      data y_data(   120,   4) /   0.482174393880D-02/
      data y_data(   120,   5) /   0.189891105857D+00/
      data y_data(   120,   6) /   0.169831629724D-08/
      data y_data(   120,   7) /   0.836092647691D-02/
      data y_data(   120,   8) /   0.854814519436D-01/
      data y_data(   120,   9) /   0.711444770086D+00/
c                                                 
c     interpolation routine                       
c                                                 
      lo_loside = 0
      lo_hiside = 0
      hi_loside = 0
      hi_hiside = 0
      if (xlo .le. x_data(1)) then
         lo_loside = 1
         lo_hiside = 1
      end if
      if (xhi .le. x_data(1)) then
         hi_loside = 1
         hi_hiside = 1
      end if
      if (xlo .ge. x_data(N)) then
         lo_loside = N
         lo_hiside = N
      end if
      if (xhi .ge. x_data(N)) then
         hi_loside = N
         hi_hiside = N
      end if
      if (lo_loside.eq.0) then
         do i = 1, N-1                           
            if ( (xlo .ge. x_data(i))
     &           .and.
     &           (xlo .le. x_data(i+1)) ) then
               lo_loside  = i
               lo_hiside  = i+1
            end if
         end do
      end if
      if (hi_loside.eq.0) then            
         do i = 1, N-1                           
            if ( (xhi .ge. x_data(i))
     &           .and.
     &           (xhi .le. x_data(i+1)) ) then
               hi_loside = i
               hi_hiside = i + 1
            end if
         end do
      end if
         
      do j = 1, M
         
         x1 = x_data(lo_loside)
         y1 = y_data(lo_loside,j)
         
         x2 = x_data(lo_hiside)
         y2 = y_data(lo_hiside,j)
          
         if (lo_loside.eq.lo_hiside) then
            dydx = 0.d0
         else
            dydx = (y2-y1)/(x2-x1)
         end if
         
         ylo = y1 + dydx*(xlo - x1)
         
         if (lo_loside .eq. hi_loside) then
            
            yhi = y1 + dydx*(xhi - x1)
            
            y_vector(j) = 0.5d0*(ylo + yhi)
            
         else
            
            sum = (x2 - xlo) * 0.5d0 * (ylo + y2)
            
            x1 = x_data(hi_loside)
            y1 = y_data(hi_loside,j)
         
            x2 = x_data(hi_hiside)
            y2 = y_data(hi_hiside,j)
            
            if (hi_loside.eq.hi_hiside) then
               dydx = 0.d0
            else
               dydx = (y2-y1)/(x2-x1)
            end if
            
            yhi = y1 + dydx*(xhi - x1)
            
            sum = sum + (xhi - x1)*0.5d0*(yhi+y1)
            
            do k = lo_hiside,hi_loside-1
               
               sum = sum + (x_data(k+1)-x_data(k))
     &              * 0.5d0
     &              * (y_data(k,j) + y_data(k+1,j))
               
            end do
            
            y_vector(j) = sum / (xhi - xlo)
            
         end if
      end do
      end                                         
c     LAST LINE                                   
c-------------------------------------------------
