c-------------------------------------------------
c                                                 
c                                                 
c                              -USAGE-            
c                                                 
c     OVERVIEW: call pmf       (xlo,xhi,y,Niny)   
c     computes y(xlo,xhi) by averaging data over  
c     the range [xlo,xhi]. Here x is a scalar, y  
c     a vector, with Niny components used. Piece- 
c     constant Extrapolation is applied to points 
c     laying outside the range of the orig data   
c                                                 
c     domain: x in [ 0.25000E+01, 0.35000E+01]  
c     number of states in vector y:     9         
c     number of x data points:   132              
c                                                 
c     CALLING PROGRAM NEEDS: none                 
c     PROCEDURE NEEDS:  none                      
c     COMPILER NEEDS: f77, long names (14 char)   
c     SYSTEM NEEDS: none                          
c     NOTES: This routine was generated by        
c     subroutine makeRoutine.                     
c                                                 
c-------------------------------------------------
c                                                 
c                          -SPECIFICATION-        
c     SYNTAX:                                     
c     subroutine pmf       (xlo,xhi:dp,y:dp arr, Niny: int)
c     returns: none                               
c     REQUIRES: none                              
c     MODIFIES: y, N                              
c     SIGNALS: none                               
c     EFFECTS: computes the average value of y    
c     over the range [xlo,xhi] and returns number 
c     of components used, N.                      
c                                                 
c-------------------------------------------------
c                                                 
c                         -IMPLEMENTATION-        
c     AUTHOR: auto-generated by makeAveInterp     
c     MODIFICATION HISTORY: none                  
c     NOTES: interpolation x,y data is defined in 
c     data statements for efficiency.             
c     REQUIRES: none                              
c     LOCAL VARIABLES:                            
c     xlo,xhi.........(dp) average y on this range
c     y_vector........(1D dp arr) computed y(x)   
c     Niny............(int) no. of used components
c     x_data..........(dp) x data points          
c     y_data..........(dp) y(x) data points       
c     N...............(int) number of x points    
c     M...............(int) dimension of y_data   
c     i,j,k...........(int) loop index            
c     lo_{lo,hi}side..(int) idx of data near xlo  
c     hi_{lo,hi}side..(int) idx of data near xhi  
c     x1..............(dp) interpolation point    
c     x2..............(dp) interpolation point    
c     y1..............(dp) interpolation value    
c     y2..............(dp) interpolation value    
c     dydx............(dp) slope of linear interp 
c     ylo.............(dp) value at xlo           
c     yhi.............(dp) value at xhi           
c     GLOBAL VARIABLES:none                       
c     PROCEDURES: none                            
c     FILES: none                                 
c     I/O: none                                   
c-------------------------------------------------
c                                                 
c                             -CODE-              
c     FIRST LINE:                                 
      subroutine pmf       (xlo,xhi,y_vector,Niny)
c                                                 
c     declare local variables                     
c                                                 
      integer N,M,i,j,k,lo_loside,lo_hiside       
      integer hi_loside,hi_hiside,Niny            
      double precision xlo,xhi,y_vector(*),sum    
      double precision ylo,yhi,x1,y1,x2,y2,dydx   
      double precision x_data(   132)              
      double precision y_data(   132,     9)        
      data N,M /   132,     9/                   
      Niny =      9                                
c                                                 
c     interpolation x,y data                      
c                                                 
      data x_data(     1     ) /   0.250000000000D+01/
      data y_data(     1,   1) /   0.298000000000D+03/
      data y_data(     1,   2) /   0.268023278035D+02/
      data y_data(     1,   3) /   0.113923111187D-02/
      data y_data(     1,   4) /   0.193726934051D+00/
      data y_data(     1,   5) /   0.118145975412D-07/
      data y_data(     1,   6) /   0.774907691024D-01/
      data y_data(     1,   7) /   0.285644089764D-09/
      data y_data(     1,   8) /   0.722809262623D-10/
      data y_data(     1,   9) /   0.728782284674D+00/
      data x_data(     2     ) /   0.266666666667D+01/
      data y_data(     2,   1) /   0.298001667224D+03/
      data y_data(     2,   2) /   0.268024789734D+02/
      data y_data(     2,   3) /   0.113922468644D-02/
      data y_data(     2,   4) /   0.193726864034D+00/
      data y_data(     2,   5) /   0.247920173617D-06/
      data y_data(     2,   6) /   0.774906571489D-01/
      data y_data(     2,   7) /   0.646707092889D-08/
      data y_data(     2,   8) /   0.213360114878D-08/
      data y_data(     2,   9) /   0.728782222297D+00/
      data x_data(     3     ) /   0.283333333333D+01/
      data y_data(     3,   1) /   0.298037037202D+03/
      data y_data(     3,   2) /   0.268056868682D+02/
      data y_data(     3,   3) /   0.113908835295D-02/
      data y_data(     3,   4) /   0.193725269649D+00/
      data y_data(     3,   5) /   0.520210236014D-05/
      data y_data(     3,   6) /   0.774883872473D-01/
      data y_data(     3,   7) /   0.146409787256D-06/
      data y_data(     3,   8) /   0.629767555862D-07/
      data y_data(     3,   9) /   0.728780931615D+00/
      data x_data(     4     ) /   0.287500000000D+01/
      data y_data(     4,   1) /   0.298157573420D+03/
      data y_data(     4,   2) /   0.268166214199D+02/
      data y_data(     4,   3) /   0.113862388651D-02/
      data y_data(     4,   4) /   0.193719444400D+00/
      data y_data(     4,   5) /   0.219048948420D-04/
      data y_data(     4,   6) /   0.774809875324D-01/
      data y_data(     4,   7) /   0.654458762105D-06/
      data y_data(     4,   8) /   0.349223702778D-06/
      data y_data(     4,   9) /   0.728776659490D+00/
      data x_data(     5     ) /   0.291666666667D+01/
      data y_data(     5,   1) /   0.298886306821D+03/
      data y_data(     5,   2) /   0.268827412060D+02/
      data y_data(     5,   3) /   0.113582336973D-02/
      data y_data(     5,   4) /   0.193681911060D+00/
      data y_data(     5,   5) /   0.121885334989D-03/
      data y_data(     5,   6) /   0.774380131604D-01/
      data y_data(     5,   7) /   0.390684249846D-05/
      data y_data(     5,   8) /   0.267286640772D-05/
      data y_data(     5,   9) /   0.728751610735D+00/
      data x_data(     6     ) /   0.293750000000D+01/
      data y_data(     6,   1) /   0.300624187510D+03/
      data y_data(     6,   2) /   0.270404499320D+02/
      data y_data(     6,   3) /   0.112919887728D-02/
      data y_data(     6,   4) /   0.193586770298D+00/
      data y_data(     6,   5) /   0.357884124560D-03/
      data y_data(     6,   6) /   0.773393840815D-01/
      data y_data(     6,   7) /   0.120965925836D-04/
      data y_data(     6,   8) /   0.100118368442D-04/
      data y_data(     6,   9) /   0.728693853066D+00/
      data x_data(     7     ) /   0.294791666667D+01/
      data y_data(     7,   1) /   0.303118559472D+03/
      data y_data(     7,   2) /   0.272668404296D+02/
      data y_data(     7,   3) /   0.111982339073D-02/
      data y_data(     7,   4) /   0.193443066721D+00/
      data y_data(     7,   5) /   0.693293242866D-03/
      data y_data(     7,   6) /   0.772022681686D-01/
      data y_data(     7,   7) /   0.243954171966D-04/
      data y_data(     7,   8) /   0.233624066541D-04/
      data y_data(     7,   9) /   0.728613614044D+00/
      data x_data(     8     ) /   0.295833333333D+01/
      data y_data(     8,   1) /   0.308674173937D+03/
      data y_data(     8,   2) /   0.277711607048D+02/
      data y_data(     8,   3) /   0.109948755937D-02/
      data y_data(     8,   4) /   0.193108763608D+00/
      data y_data(     8,   5) /   0.143242872486D-02/
      data y_data(     8,   6) /   0.769051265522D-01/
      data y_data(     8,   7) /   0.528754341263D-04/
      data y_data(     8,   8) /   0.598338901430D-04/
      data y_data(     8,   9) /   0.728440971791D+00/
      data x_data(     9     ) /   0.296354166667D+01/
      data y_data(     9,   1) /   0.313957592211D+03/
      data y_data(     9,   2) /   0.282508630592D+02/
      data y_data(     9,   3) /   0.108081815555D-02/
      data y_data(     9,   4) /   0.192778668504D+00/
      data y_data(     9,   5) /   0.212707020858D-02/
      data y_data(     9,   6) /   0.766292803656D-01/
      data y_data(     9,   7) /   0.808977738182D-04/
      data y_data(     9,   8) /   0.101288457383D-03/
      data y_data(     9,   9) /   0.728282794691D+00/
      data x_data(    10     ) /   0.296875000000D+01/
      data y_data(    10,   1) /   0.322321907380D+03/
      data y_data(    10,   2) /   0.290104586306D+02/
      data y_data(    10,   3) /   0.105251854489D-02/
      data y_data(    10,   4) /   0.192240454919D+00/
      data y_data(    10,   5) /   0.321357133526D-02/
      data y_data(    10,   6) /   0.762008826090D-01/
      data y_data(    10,   7) /   0.126493404996D-03/
      data y_data(    10,   8) /   0.176943785461D-03/
      data y_data(    10,   9) /   0.728041653947D+00/
      data x_data(    11     ) /   0.297135416667D+01/
      data y_data(    11,   1) /   0.328281646614D+03/
      data y_data(    11,   2) /   0.295517958678D+02/
      data y_data(    11,   3) /   0.103323824518D-02/
      data y_data(    11,   4) /   0.191847658486D+00/
      data y_data(    11,   5) /   0.397843334726D-02/
      data y_data(    11,   6) /   0.759004723304D-01/
      data y_data(    11,   7) /   0.159729850189D-03/
      data y_data(    11,   8) /   0.237551973845D-03/
      data y_data(    11,   9) /   0.727876154012D+00/
      data x_data(    12     ) /   0.297395833333D+01/
      data y_data(    12,   1) /   0.335874426866D+03/
      data y_data(    12,   2) /   0.302415926040D+02/
      data y_data(    12,   3) /   0.100967055883D-02/
      data y_data(    12,   4) /   0.191338330123D+00/
      data y_data(    12,   5) /   0.494275847872D-02/
      data y_data(    12,   6) /   0.755221970965D-01/
      data y_data(    12,   7) /   0.202807881228D-03/
      data y_data(    12,   8) /   0.321780161639D-03/
      data y_data(    12,   9) /   0.727672126259D+00/
      data x_data(    13     ) /   0.297656250000D+01/
      data y_data(    13,   1) /   0.345474449696D+03/
      data y_data(    13,   2) /   0.311139489293D+02/
      data y_data(    13,   3) /   0.981361953564D-03/
      data y_data(    13,   4) /   0.190683087945D+00/
      data y_data(    13,   5) /   0.614755807136D-02/
      data y_data(    13,   6) /   0.750494201977D-01/
      data y_data(    13,   7) /   0.258231936023D-03/
      data y_data(    13,   8) /   0.437782601104D-03/
      data y_data(    13,   9) /   0.727423919249D+00/
      data x_data(    14     ) /   0.297916666667D+01/
      data y_data(    14,   1) /   0.357503294896D+03/
      data y_data(    14,   2) /   0.322073321608D+02/
      data y_data(    14,   3) /   0.948046412284D-03/
      data y_data(    14,   4) /   0.189847934874D+00/
      data y_data(    14,   5) /   0.763685362604D-02/
      data y_data(    14,   6) /   0.744637009653D-01/
      data y_data(    14,   7) /   0.328922728887D-03/
      data y_data(    14,   8) /   0.595853197022D-03/
      data y_data(    14,   9) /   0.727126734608D+00/
      data x_data(    15     ) /   0.298177083333D+01/
      data y_data(    15,   1) /   0.372418493492D+03/
      data y_data(    15,   2) /   0.335635614616D+02/
      data y_data(    15,   3) /   0.909737953145D-03/
      data y_data(    15,   4) /   0.188794796652D+00/
      data y_data(    15,   5) /   0.945558070839D-02/
      data y_data(    15,   6) /   0.737453310291D-01/
      data y_data(    15,   7) /   0.418185417179D-03/
      data y_data(    15,   8) /   0.808617765448D-03/
      data y_data(    15,   9) /   0.726777488428D+00/
      data x_data(    16     ) /   0.298437500000D+01/
      data y_data(    16,   1) /   0.390695184575D+03/
      data y_data(    16,   2) /   0.352261635216D+02/
      data y_data(    16,   3) /   0.866800203365D-03/
      data y_data(    16,   4) /   0.187482564166D+00/
      data y_data(    16,   5) /   0.116468748826D-01/
      data y_data(    16,   6) /   0.728741061127D-01/
      data y_data(    16,   7) /   0.529636171262D-03/
      data y_data(    16,   8) /   0.109107580097D-02/
      data y_data(    16,   9) /   0.726375742867D+00/
      data x_data(    17     ) /   0.298567708333D+01/
      data y_data(    17,   1) /   0.401300983747D+03/
      data y_data(    17,   2) /   0.361912852075D+02/
      data y_data(    17,   3) /   0.843685034375D-03/
      data y_data(    17,   4) /   0.186711062602D+00/
      data y_data(    17,   5) /   0.129004494904D-01/
      data y_data(    17,   6) /   0.723724415042D-01/
      data y_data(    17,   7) /   0.595286873024D-03/
      data y_data(    17,   8) /   0.126547428417D-02/
      data y_data(    17,   9) /   0.726155285246D+00/
      data x_data(    18     ) /   0.298697916667D+01/
      data y_data(    18,   1) /   0.412986908596D+03/
      data y_data(    18,   2) /   0.372549596554D+02/
      data y_data(    18,   3) /   0.819596799640D-03/
      data y_data(    18,   4) /   0.185853032225D+00/
      data y_data(    18,   5) /   0.142674305721D-01/
      data y_data(    18,   6) /   0.718224380342D-01/
      data y_data(    18,   7) /   0.668412541619D-03/
      data y_data(    18,   8) /   0.146610812763D-02/
      data y_data(    18,   9) /   0.725922578500D+00/
      data x_data(    19     ) /   0.298828125000D+01/
      data y_data(    19,   1) /   0.425812439156D+03/
      data y_data(    19,   2) /   0.384226696430D+02/
      data y_data(    19,   3) /   0.794688291782D-03/
      data y_data(    19,   4) /   0.184902472463D+00/
      data y_data(    19,   5) /   0.157517667404D-01/
      data y_data(    19,   6) /   0.712216003499D-01/
      data y_data(    19,   7) /   0.749561243710D-03/
      data y_data(    19,   8) /   0.169585029565D-02/
      data y_data(    19,   9) /   0.725678748907D+00/
      data x_data(    20     ) /   0.298958333333D+01/
      data y_data(    20,   1) /   0.439832590559D+03/
      data y_data(    20,   2) /   0.396994987314D+02/
      data y_data(    20,   3) /   0.769129250496D-03/
      data y_data(    20,   4) /   0.183853535813D+00/
      data y_data(    20,   5) /   0.173566937587D-01/
      data y_data(    20,   6) /   0.705676012515D-01/
      data y_data(    20,   7) /   0.839273424211D-03/
      data y_data(    20,   8) /   0.195768267539D-02/
      data y_data(    20,   9) /   0.725425213077D+00/
      data x_data(    21     ) /   0.299088541667D+01/
      data y_data(    21,   1) /   0.455097115008D+03/
      data y_data(    21,   2) /   0.410900572199D+02/
      data y_data(    21,   3) /   0.743100588566D-03/
      data y_data(    21,   4) /   0.182700591946D+00/
      data y_data(    21,   5) /   0.190846957006D-01/
      data y_data(    21,   6) /   0.698583055623D-01/
      data y_data(    21,   7) /   0.938076182148D-03/
      data y_data(    21,   8) /   0.225467088913D-02/
      data y_data(    21,   9) /   0.725163659720D+00/
      data x_data(    22     ) /   0.299218750000D+01/
      data y_data(    22,   1) /   0.471649900804D+03/
      data y_data(    22,   2) /   0.425984255302D+02/
      data y_data(    22,   3) /   0.716788128300D-03/
      data y_data(    22,   4) /   0.181438278641D+00/
      data y_data(    22,   5) /   0.209374980302D-01/
      data y_data(    22,   6) /   0.690917847270D-01/
      data y_data(    22,   7) /   0.104647850297D-02/
      data y_data(    22,   8) /   0.258993985279D-02/
      data y_data(    22,   9) /   0.724896020246D+00/
      data x_data(    23     ) /   0.299348958333D+01/
      data y_data(    23,   1) /   0.489528580465D+03/
      data y_data(    23,   2) /   0.442281161147D+02/
      data y_data(    23,   3) /   0.690376357544D-03/
      data y_data(    23,   4) /   0.180061544888D+00/
      data y_data(    23,   5) /   0.229160828415D-01/
      data y_data(    23,   6) /   0.682663256729D-01/
      data y_data(    23,   7) /   0.116496700660D-02/
      data y_data(    23,   8) /   0.296664892165D-02/
      data y_data(    23,   9) /   0.724624430669D+00/
      data x_data(    24     ) /   0.299479166667D+01/
      data y_data(    24,   1) /   0.508764370975D+03/
      data y_data(    24,   2) /   0.459820560733D+02/
      data y_data(    24,   3) /   0.664042635581D-03/
      data y_data(    24,   4) /   0.178565678865D+00/
      data y_data(    24,   5) /   0.250207308379D-01/
      data y_data(    24,   6) /   0.673804307885D-01/
      data y_data(    24,   7) /   0.129400288985D-02/
      data y_data(    24,   8) /   0.338796988096D-02/
      data y_data(    24,   9) /   0.724351186737D+00/
      data x_data(    25     ) /   0.299609375000D+01/
      data y_data(    25,   1) /   0.529382126409D+03/
      data y_data(    25,   2) /   0.478625887417D+02/
      data y_data(    25,   3) /   0.637952240091D-03/
      data y_data(    25,   4) /   0.176946326830D+00/
      data y_data(    25,   5) /   0.272510788327D-01/
      data y_data(    25,   6) /   0.664328128821D-01/
      data y_data(    25,   7) /   0.143401957672D-02/
      data y_data(    25,   8) /   0.385706649132D-02/
      data y_data(    25,   9) /   0.724078695387D+00/
      data x_data(    26     ) /   0.299739583333D+01/
      data y_data(    26,   1) /   0.551400591818D+03/
      data y_data(    26,   2) /   0.498714933570D+02/
      data y_data(    26,   3) /   0.612254489469D-03/
      data y_data(    26,   4) /   0.175199498639D+00/
      data y_data(    26,   5) /   0.296061931688D-01/
      data y_data(    26,   6) /   0.654223835679D-01/
      data y_data(    26,   7) /   0.158542150664D-02/
      data y_data(    26,   8) /   0.437707801465D-02/
      data y_data(    26,   9) /   0.723809425103D+00/
      data x_data(    27     ) /   0.299869791667D+01/
      data y_data(    27,   1) /   0.574832814650D+03/
      data y_data(    27,   2) /   0.520100189106D+02/
      data y_data(    27,   3) /   0.587080073107D-03/
      data y_data(    27,   4) /   0.173321565995D+00/
      data y_data(    27,   5) /   0.320846487167D-01/
      data y_data(    27,   6) /   0.643482387251D-01/
      data y_data(    27,   7) /   0.174858356351D-02/
      data y_data(    27,   8) /   0.495110521921D-02/
      data y_data(    27,   9) /   0.723545857780D+00/
      data x_data(    28     ) /   0.300000000000D+01/
      data y_data(    28,   1) /   0.599686681382D+03/
      data y_data(    28,   2) /   0.542789293539D+02/
      data y_data(    28,   3) /   0.562539572312D-03/
      data y_data(    28,   4) /   0.171309251372D+00/
      data y_data(    28,   5) /   0.346846122811D-01/
      data y_data(    28,   6) /   0.632096404530D-01/
      data y_data(    28,   7) /   0.192385137046D-02/
      data y_data(    28,   8) /   0.558220036159D-02/
      data y_data(    28,   9) /   0.723290444161D+00/
      data x_data(    29     ) /   0.300003796203D+01/
      data y_data(    29,   1) /   0.600433422827D+03/
      data y_data(    29,   2) /   0.543471079571D+02/
      data y_data(    29,   3) /   0.561833864801D-03/
      data y_data(    29,   4) /   0.171248467334D+00/
      data y_data(    29,   5) /   0.347622687739D-01/
      data y_data(    29,   6) /   0.631754420127D-01/
      data y_data(    29,   7) /   0.192915224886D-02/
      data y_data(    29,   8) /   0.560152202245D-02/
      data y_data(    29,   9) /   0.723283147608D+00/
      data x_data(    30     ) /   0.300007592406D+01/
      data y_data(    30,   1) /   0.601181432723D+03/
      data y_data(    30,   2) /   0.544154028185D+02/
      data y_data(    30,   3) /   0.561128726845D-03/
      data y_data(    30,   4) /   0.171187560493D+00/
      data y_data(    30,   5) /   0.348400308148D-01/
      data y_data(    30,   6) /   0.631411857951D-01/
      data y_data(    30,   7) /   0.193446422955D-02/
      data y_data(    30,   8) /   0.562089807632D-02/
      data y_data(    30,   9) /   0.723275860591D+00/
      data x_data(    31     ) /   0.300015184812D+01/
      data y_data(    31,   1) /   0.602681253878D+03/
      data y_data(    31,   2) /   0.545523409567D+02/
      data y_data(    31,   3) /   0.559720172752D-03/
      data y_data(    31,   4) /   0.171065378470D+00/
      data y_data(    31,   5) /   0.349958710028D-01/
      data y_data(    31,   6) /   0.630725001335D-01/
      data y_data(    31,   7) /   0.194512149747D-02/
      data y_data(    31,   8) /   0.565981349687D-02/
      data y_data(    31,   9) /   0.723261315399D+00/
      data x_data(    32     ) /   0.300030369624D+01/
      data y_data(    32,   1) /   0.605696064635D+03/
      data y_data(    32,   2) /   0.548276075639D+02/
      data y_data(    32,   3) /   0.556910050630D-03/
      data y_data(    32,   4) /   0.170819542702D+00/
      data y_data(    32,   5) /   0.353088113398D-01/
      data y_data(    32,   6) /   0.629344370873D-01/
      data y_data(    32,   7) /   0.196656915557D-02/
      data y_data(    32,   8) /   0.573829788284D-02/
      data y_data(    32,   9) /   0.723232341833D+00/
      data x_data(    33     ) /   0.300060739247D+01/
      data y_data(    33,   1) /   0.611786063770D+03/
      data y_data(    33,   2) /   0.553836754349D+02/
      data y_data(    33,   3) /   0.551318515150D-03/
      data y_data(    33,   4) /   0.170321997426D+00/
      data y_data(    33,   5) /   0.359396963401D-01/
      data y_data(    33,   6) /   0.626555535607D-01/
      data y_data(    33,   7) /   0.200999611916D-02/
      data y_data(    33,   8) /   0.589788308642D-02/
      data y_data(    33,   9) /   0.723174873468D+00/
      data x_data(    34     ) /   0.300121478495D+01/
      data y_data(    34,   1) /   0.624205203258D+03/
      data y_data(    34,   2) /   0.565177362970D+02/
      data y_data(    34,   3) /   0.540255992276D-03/
      data y_data(    34,   4) /   0.169303518527D+00/
      data y_data(    34,   5) /   0.372212026589D-01/
      data y_data(    34,   6) /   0.620868322161D-01/
      data y_data(    34,   7) /   0.209896974696D-02/
      data y_data(    34,   8) /   0.622753576869D-02/
      data y_data(    34,   9) /   0.723061941083D+00/
      data x_data(    35     ) /   0.300182217742D+01/
      data y_data(    35,   1) /   0.636942227750D+03/
      data y_data(    35,   2) /   0.576809429419D+02/
      data y_data(    35,   3) /   0.529361070519D-03/
      data y_data(    35,   4) /   0.168253751753D+00/
      data y_data(    35,   5) /   0.385287318570D-01/
      data y_data(    35,   6) /   0.615035158530D-01/
      data y_data(    35,   7) /   0.219078359027D-02/
      data y_data(    35,   8) /   0.657135751456D-02/
      data y_data(    35,   9) /   0.722951859432D+00/
      data x_data(    36     ) /   0.300212587366D+01/
      data y_data(    36,   1) /   0.643430830243D+03/
      data y_data(    36,   2) /   0.582735547718D+02/
      data y_data(    36,   3) /   0.523977742973D-03/
      data y_data(    36,   4) /   0.167716963721D+00/
      data y_data(    36,   5) /   0.391922344179D-01/
      data y_data(    36,   6) /   0.612063340723D-01/
      data y_data(    36,   7) /   0.223777270757D-02/
      data y_data(    36,   8) /   0.674872928188D-02/
      data y_data(    36,   9) /   0.722897965799D+00/
      data x_data(    37     ) /   0.300227772177D+01/
      data y_data(    37,   1) /   0.646705323223D+03/
      data y_data(    37,   2) /   0.585726277603D+02/
      data y_data(    37,   3) /   0.521302302319D-03/
      data y_data(    37,   4) /   0.167445556694D+00/
      data y_data(    37,   5) /   0.395264186348D-01/
      data y_data(    37,   6) /   0.610563511582D-01/
      data y_data(    37,   7) /   0.226154143869D-02/
      data y_data(    37,   8) /   0.683881105901D-02/
      data y_data(    37,   9) /   0.722871321016D+00/
      data x_data(    38     ) /   0.300235364583D+01/
      data y_data(    38,   1) /   0.648350138158D+03/
      data y_data(    38,   2) /   0.587228578258D+02/
      data y_data(    38,   3) /   0.519968660158D-03/
      data y_data(    38,   4) /   0.167309095317D+00/
      data y_data(    38,   5) /   0.396941187195D-01/
      data y_data(    38,   6) /   0.609810103150D-01/
      data y_data(    38,   7) /   0.227349480110D-02/
      data y_data(    38,   8) /   0.688420481242D-02/
      data y_data(    38,   9) /   0.722858076035D+00/
      data x_data(    39     ) /   0.300242956989D+01/
      data y_data(    39,   1) /   0.650000000000D+03/
      data y_data(    39,   2) /   0.588735503694D+02/
      data y_data(    39,   3) /   0.518637750106D-03/
      data y_data(    39,   4) /   0.167172127567D+00/
      data y_data(    39,   5) /   0.398622235848D-01/
      data y_data(    39,   6) /   0.609054362814D-01/
      data y_data(    39,   7) /   0.228549427867D-02/
      data y_data(    39,   8) /   0.692983495201D-02/
      data y_data(    39,   9) /   0.722844883337D+00/
      data x_data(    40     ) /   0.300371267221D+01/
      data y_data(    40,   1) /   0.678619932453D+03/
      data y_data(    40,   2) /   0.614878455364D+02/
      data y_data(    40,   3) /   0.496586690230D-03/
      data y_data(    40,   4) /   0.164782640406D+00/
      data y_data(    40,   5) /   0.427622527237D-01/
      data y_data(    40,   6) /   0.595938692137D-01/
      data y_data(    40,   7) /   0.249510584971D-02/
      data y_data(    40,   8) /   0.773604974104D-02/
      data y_data(    40,   9) /   0.722630082066D+00/
      data x_data(    41     ) /   0.300499577453D+01/
      data y_data(    41,   1) /   0.708616202376D+03/
      data y_data(    41,   2) /   0.642283213709D+02/
      data y_data(    41,   3) /   0.475398469906D-03/
      data y_data(    41,   4) /   0.162252702517D+00/
      data y_data(    41,   5) /   0.457710083246D-01/
      data y_data(    41,   6) /   0.582179965775D-01/
      data y_data(    41,   7) /   0.271756982451D-02/
      data y_data(    41,   8) /   0.860911576899D-02/
      data y_data(    41,   9) /   0.722431606988D+00/
      data x_data(    42     ) /   0.300627887685D+01/
      data y_data(    42,   1) /   0.739980529160D+03/
      data y_data(    42,   2) /   0.670941467471D+02/
      data y_data(    42,   3) /   0.455092540627D-03/
      data y_data(    42,   4) /   0.159580565086D+00/
      data y_data(    42,   5) /   0.488857975901D-01/
      data y_data(    42,   6) /   0.567776427118D-01/
      data y_data(    42,   7) /   0.295309491942D-02/
      data y_data(    42,   8) /   0.955168073805D-02/
      data y_data(    42,   9) /   0.722251218955D+00/
      data x_data(    43     ) /   0.300756197917D+01/
      data y_data(    43,   1) /   0.772703058444D+03/
      data y_data(    43,   2) /   0.700843146726D+02/
      data y_data(    43,   3) /   0.435675883355D-03/
      data y_data(    43,   4) /   0.156764699248D+00/
      data y_data(    43,   5) /   0.521038953733D-01/
      data y_data(    43,   6) /   0.552726925754D-01/
      data y_data(    43,   7) /   0.320186861318D-02/
      data y_data(    43,   8) /   0.105663341792D-01/
      data y_data(    43,   9) /   0.722090510010D+00/
      data x_data(    44     ) /   0.300884508149D+01/
      data y_data(    44,   1) /   0.806772703713D+03/
      data y_data(    44,   2) /   0.731976709440D+02/
      data y_data(    44,   3) /   0.417145044515D-03/
      data y_data(    44,   4) /   0.153803780626D+00/
      data y_data(    44,   5) /   0.554225728063D-01/
      data y_data(    44,   6) /   0.537030820463D-01/
      data y_data(    44,   7) /   0.346405649365D-02/
      data y_data(    44,   8) /   0.116556098835D-01/
      data y_data(    44,   9) /   0.721950898144D+00/
      data x_data(    45     ) /   0.301012818380D+01/
      data y_data(    45,   1) /   0.842177358913D+03/
      data y_data(    45,   2) /   0.764329311373D+02/
      data y_data(    45,   3) /   0.399488090408D-03/
      data y_data(    45,   4) /   0.150696679944D+00/
      data y_data(    45,   5) /   0.588391144640D-01/
      data y_data(    45,   6) /   0.520687925248D-01/
      data y_data(    45,   7) /   0.373979860114D-02/
      data y_data(    45,   8) /   0.128219886735D-01/
      data y_data(    45,   9) /   0.721833625793D+00/
      data x_data(    46     ) /   0.301141128612D+01/
      data y_data(    46,   1) /   0.878903935542D+03/
      data y_data(    46,   2) /   0.797886815725D+02/
      data y_data(    46,   3) /   0.382686429986D-03/
      data y_data(    46,   4) /   0.147442464815D+00/
      data y_data(    46,   5) /   0.623508202146D-01/
      data y_data(    46,   6) /   0.503698525908D-01/
      data y_data(    46,   7) /   0.402919965381D-02/
      data y_data(    46,   8) /   0.140679011370D-01/
      data y_data(    46,   9) /   0.721739761589D+00/
      data x_data(    47     ) /   0.301269438844D+01/
      data y_data(    47,   1) /   0.916938144472D+03/
      data y_data(    47,   2) /   0.832633567640D+02/
      data y_data(    47,   3) /   0.366716487192D-03/
      data y_data(    47,   4) /   0.144040421776D+00/
      data y_data(    47,   5) /   0.659549840961D-01/
      data y_data(    47,   6) /   0.486063517779D-01/
      data y_data(    47,   7) /   0.433230762622D-02/
      data y_data(    47,   8) /   0.153957296944D-01/
      data y_data(    47,   9) /   0.721670205029D+00/
      data x_data(    48     ) /   0.301333593960D+01/
      data y_data(    48,   1) /   0.936447962983D+03/
      data y_data(    48,   2) /   0.850453955168D+02/
      data y_data(    48,   3) /   0.359032320548D-03/
      data y_data(    48,   4) /   0.142283141757D+00/
      data y_data(    48,   5) /   0.677912388834D-01/
      data y_data(    48,   6) /   0.477001786700D-01/
      data y_data(    48,   7) /   0.448903911992D-02/
      data y_data(    48,   8) /   0.160915532024D-01/
      data y_data(    48,   9) /   0.721644848367D+00/
      data x_data(    49     ) /   0.301397749076D+01/
      data y_data(    49,   1) /   0.956284000291D+03/
      data y_data(    49,   2) /   0.868569643067D+02/
      data y_data(    49,   3) /   0.351544012021D-03/
      data y_data(    49,   4) /   0.140488072199D+00/
      data y_data(    49,   5) /   0.696498631537D-01/
      data y_data(    49,   6) /   0.467776829243D-01/
      data y_data(    49,   7) /   0.464922673588D-02/
      data y_data(    49,   8) /   0.168092235980D-01/
      data y_data(    49,   9) /   0.721625931390D+00/
      data x_data(    50     ) /   0.301461904192D+01/
      data y_data(    50,   1) /   0.976443621546D+03/
      data y_data(    50,   2) /   0.886977746453D+02/
      data y_data(    50,   3) /   0.344248159849D-03/
      data y_data(    50,   4) /   0.138655224728D+00/
      data y_data(    50,   5) /   0.715304650949D-01/
      data y_data(    50,   6) /   0.458389180061D-01/
      data y_data(    50,   7) /   0.481283436195D-02/
      data y_data(    50,   8) /   0.175490357429D-01/
      data y_data(    50,   9) /   0.721613522067D+00/
      data x_data(    51     ) /   0.301526059308D+01/
      data y_data(    51,   1) /   0.996923873161D+03/
      data y_data(    51,   2) /   0.905675053528D+02/
      data y_data(    51,   3) /   0.337141291298D-03/
      data y_data(    51,   4) /   0.136784649129D+00/
      data y_data(    51,   5) /   0.734326295320D-01/
      data y_data(    51,   6) /   0.448839552231D-01/
      data y_data(    51,   7) /   0.497980686603D-02/
      data y_data(    51,   8) /   0.183112801767D-01/
      data y_data(    51,   9) /   0.721607679073D+00/
      data x_data(    52     ) /   0.301590214424D+01/
      data y_data(    52,   1) /   0.101772138990D+04/
      data y_data(    52,   2) /   0.924657938276D+02/
      data y_data(    52,   3) /   0.330219905549D-03/
      data y_data(    52,   4) /   0.134876442910D+00/
      data y_data(    52,   5) /   0.753559088382D-01/
      data y_data(    52,   6) /   0.439128892197D-01/
      data y_data(    52,   7) /   0.515006443279D-02/
      data y_data(    52,   8) /   0.190962423712D-01/
      data y_data(    52,   9) /   0.721608452228D+00/
      data x_data(    53     ) /   0.301654369540D+01/
      data y_data(    53,   1) /   0.103883207719D+04/
      data y_data(    53,   2) /   0.943922068372D+02/
      data y_data(    53,   3) /   0.323480578826D-03/
      data y_data(    53,   4) /   0.132930763252D+00/
      data y_data(    53,   5) /   0.772998117169D-01/
      data y_data(    53,   6) /   0.429258448087D-01/
      data y_data(    53,   7) /   0.532349560991D-02/
      data y_data(    53,   8) /   0.199042016806D-01/
      data y_data(    53,   9) /   0.721615882932D+00/
      data x_data(    54     ) /   0.301718524656D+01/
      data y_data(    54,   1) /   0.106025119667D+04/
      data y_data(    54,   2) /   0.963462478737D+02/
      data y_data(    54,   3) /   0.316919925562D-03/
      data y_data(    54,   4) /   0.130947841854D+00/
      data y_data(    54,   5) /   0.792637893915D-01/
      data y_data(    54,   6) /   0.419229854165D-01/
      data y_data(    54,   7) /   0.549994892332D-02/
      data y_data(    54,   8) /   0.207354298057D-01/
      data y_data(    54,   9) /   0.721630004609D+00/
      data x_data(    55     ) /   0.301782679772D+01/
      data y_data(    55,   1) /   0.108197324766D+04/
      data y_data(    55,   2) /   0.983273459135D+02/
      data y_data(    55,   3) /   0.310534627175D-03/
      data y_data(    55,   4) /   0.128928003204D+00/
      data y_data(    55,   5) /   0.812472187621D-01/
      data y_data(    55,   6) /   0.409045234018D-01/
      data y_data(    55,   7) /   0.567922296532D-02/
      data y_data(    55,   8) /   0.215901885437D-01/
      data y_data(    55,   9) /   0.721650843124D+00/
      data x_data(    56     ) /   0.301846834887D+01/
      data y_data(    56,   1) /   0.110399177755D+04/
      data y_data(    56,   2) /   0.100334837652D+03/
      data y_data(    56,   3) /   0.304321474163D-03/
      data y_data(    56,   4) /   0.126871686417D+00/
      data y_data(    56,   5) /   0.832493824866D-01/
      data y_data(    56,   6) /   0.398707323177D-01/
      data y_data(    56,   7) /   0.586105495965D-02/
      data y_data(    56,   8) /   0.224687266835D-01/
      data y_data(    56,   9) /   0.721678417136D+00/
      data x_data(    57     ) /   0.301910990003D+01/
      data y_data(    57,   1) /   0.112629915921D+04/
      data y_data(    57,   2) /   0.102367946682D+03/
      data y_data(    57,   3) /   0.298277407079D-03/
      data y_data(    57,   4) /   0.124779470840D+00/
      data y_data(    57,   5) /   0.852694459249D-01/
      data y_data(    57,   6) /   0.388219611808D-01/
      data y_data(    57,   7) /   0.604510790241D-02/
      data y_data(    57,   8) /   0.233712758213D-01/
      data y_data(    57,   9) /   0.721712738330D+00/
      data x_data(    58     ) /   0.301975145119D+01/
      data y_data(    58,   1) /   0.114888633468D+04/
      data y_data(    58,   2) /   0.104425759567D+03/
      data y_data(    58,   3) /   0.292399555732D-03/
      data y_data(    58,   4) /   0.122652105458D+00/
      data y_data(    58,   5) /   0.873064310112D-01/
      data y_data(    58,   6) /   0.377586507289D-01/
      data y_data(    58,   7) /   0.623095651227D-02/
      data y_data(    58,   8) /   0.242980448152D-01/
      data y_data(    58,   9) /   0.721753811474D+00/
      data x_data(    59     ) /   0.302039300235D+01/
      data y_data(    59,   1) /   0.117174252621D+04/
      data y_data(    59,   2) /   0.106507198942D+03/
      data y_data(    59,   3) /   0.286685275810D-03/
      data y_data(    59,   4) /   0.120490541971D+00/
      data y_data(    59,   5) /   0.893591873167D-01/
      data y_data(    59,   6) /   0.366813515309D-01/
      data y_data(    59,   7) /   0.641807239351D-02/
      data y_data(    59,   8) /   0.252492125593D-01/
      data y_data(    59,   9) /   0.721801634229D+00/
      data x_data(    60     ) /   0.302103455351D+01/
      data y_data(    60,   1) /   0.119485491774D+04/
      data y_data(    60,   2) /   0.108610993953D+03/
      data y_data(    60,   3) /   0.281132181863D-03/
      data y_data(    60,   4) /   0.118295971167D+00/
      data y_data(    60,   5) /   0.914263608166D-01/
      data y_data(    60,   6) /   0.355907436555D-01/
      data y_data(    60,   7) /   0.660580901414D-02/
      data y_data(    60,   8) /   0.262249187184D-01/
      data y_data(    60,   9) /   0.721856196629D+00/
      data x_data(    61     ) /   0.302167610467D+01/
      data y_data(    61,   1) /   0.121820831222D+04/
      data y_data(    61,   2) /   0.110735648604D+03/
      data y_data(    61,   3) /   0.275738175459D-03/
      data y_data(    61,   4) /   0.116069861896D+00/
      data y_data(    61,   5) /   0.935063611658D-01/
      data y_data(    61,   6) /   0.344876574268D-01/
      data y_data(    61,   7) /   0.679338732237D-02/
      data y_data(    61,   8) /   0.272252520436D-01/
      data y_data(    61,   9) /   0.721917480146D+00/
      data x_data(    62     ) /   0.302231765583D+01/
      data y_data(    62,   1) /   0.124178477343D+04/
      data y_data(    62,   2) /   0.112879408849D+03/
      data y_data(    62,   3) /   0.270501467146D-03/
      data y_data(    62,   4) /   0.113814001621D+00/
      data y_data(    62,   5) /   0.955973286117D-01/
      data y_data(    62,   6) /   0.333730945874D-01/
      data y_data(    62,   7) /   0.697988305246D-02/
      data y_data(    62,   8) /   0.282502358869D-01/
      data y_data(    62,   9) /   0.721985456240D+00/
      data x_data(    63     ) /   0.302295920699D+01/
      data y_data(    63,   1) /   0.126556326362D+04/
      data y_data(    63,   2) /   0.115040229594D+03/
      data y_data(    63,   3) /   0.265420590796D-03/
      data y_data(    63,   4) /   0.111530537151D+00/
      data y_data(    63,   5) /   0.976971020155D-01/
      data y_data(    63,   6) /   0.322482489776D-01/
      data y_data(    63,   7) /   0.716421698644D-02/
      data y_data(    63,   8) /   0.292998105648D-01/
      data y_data(    63,   9) /   0.722060084305D+00/
      data x_data(    64     ) /   0.302360075815D+01/
      data y_data(    64,   1) /   0.128951929209D+04/
      data y_data(    64,   2) /   0.117215743062D+03/
      data y_data(    64,   3) /   0.260494408915D-03/
      data y_data(    64,   4) /   0.109222013761D+00/
      data y_data(    64,   5) /   0.998031897820D-01/
      data y_data(    64,   6) /   0.311145256206D-01/
      data y_data(    64,   7) /   0.734514961256D-02/
      data y_data(    64,   8) /   0.303738122993D-01/
      data y_data(    64,   9) /   0.722141308924D+00/
      data x_data(    65     ) /   0.302424230931D+01/
      data y_data(    65,   1) /   0.131362459261D+04/
      data y_data(    65,   2) /   0.119403230287D+03/
      data y_data(    65,   3) /   0.255722107610D-03/
      data y_data(    65,   4) /   0.106891410576D+00/
      data y_data(    65,   5) /   0.101912745784D+00/
      data y_data(    65,   6) /   0.299735569202D-01/
      data y_data(    65,   7) /   0.752128172253D-02/
      data y_data(    65,   8) /   0.314719485986D-01/
      data y_data(    65,   9) /   0.722229056398D+00/
      data x_data(    66     ) /   0.302488386047D+01/
      data y_data(    66,   1) /   0.133784685051D+04/
      data y_data(    66,   2) /   0.121599597771D+03/
      data y_data(    66,   3) /   0.251103180143D-03/
      data y_data(    66,   4) /   0.104542169760D+00/
      data y_data(    66,   5) /   0.104022552575D+00/
      data y_data(    66,   6) /   0.288272145361D-01/
      data y_data(    66,   7) /   0.769106248008D-02/
      data y_data(    66,   8) /   0.325937701462D-01/
      data y_data(    66,   9) /   0.722323230503D+00/
      data x_data(    67     ) /   0.302552541163D+01/
      data y_data(    67,   1) /   0.136214950220D+04/
      data y_data(    67,   2) /   0.123801361466D+03/
      data y_data(    67,   3) /   0.246637398351D-03/
      data y_data(    67,   4) /   0.102178216892D+00/
      data y_data(    67,   5) /   0.106129014247D+00/
      data y_data(    67,   6) /   0.276776154386D-01/
      data y_data(    67,   7) /   0.785280633674D-02/
      data y_data(    67,   8) /   0.337386395518D-01/
      data y_data(    67,   9) /   0.722423707534D+00/
      data x_data(    68     ) /   0.302616696279D+01/
      data y_data(    68,   1) /   0.138649163060D+04/
      data y_data(    68,   2) /   0.126004640343D+03/
      data y_data(    68,   3) /   0.242324771700D-03/
      data y_data(    68,   4) /   0.998039698369D-01/
      data y_data(    68,   5) /   0.108228161214D+00/
      data y_data(    68,   6) /   0.265271206911D-01/
      data y_data(    68,   7) /   0.800471983771D-02/
      data y_data(    68,   8) /   0.349056976728D-01/
      data y_data(    68,   9) /   0.722530330747D+00/
      data x_data(    69     ) /   0.302680851394D+01/
      data y_data(    69,   1) /   0.141082797948D+04/
      data y_data(    69,   2) /   0.128205161661D+03/
      data y_data(    69,   3) /   0.238165494343D-03/
      data y_data(    69,   4) /   0.974243335887D-01/
      data y_data(    69,   5) /   0.110315668880D+00/
      data y_data(    69,   6) /   0.253783256765D-01/
      data y_data(    69,   7) /   0.814493883500D-02/
      data y_data(    69,   8) /   0.360938286452D-01/
      data y_data(    69,   9) /   0.722642904374D+00/
      data x_data(    70     ) /   0.302745006510D+01/
      data y_data(    70,   1) /   0.143510910680D+04/
      data y_data(    70,   2) /   0.130398279784D+03/
      data y_data(    70,   3) /   0.234159881210D-03/
      data y_data(    70,   4) /   0.950446789194D-01/
      data y_data(    70,   5) /   0.112386891635D+00/
      data y_data(    70,   6) /   0.242340408010D-01/
      data y_data(    70,   7) /   0.827157591205D-02/
      data y_data(    70,   8) /   0.373016252230D-01/
      data y_data(    70,   9) /   0.722761187509D+00/
      data x_data(    71     ) /   0.302809161626D+01/
      data y_data(    71,   1) /   0.145928169298D+04/
      data y_data(    71,   2) /   0.132579009888D+03/
      data y_data(    71,   3) /   0.230308294880D-03/
      data y_data(    71,   4) /   0.926708032858D-01/
      data y_data(    71,   5) /   0.114436912869D+00/
      data y_data(    71,   6) /   0.230972621619D-01/
      data y_data(    71,   7) /   0.838277695978D-02/
      data y_data(    71,   8) /   0.385273564871D-01/
      data y_data(    71,   9) /   0.722884888236D+00/
      data x_data(    72     ) /   0.302873316742D+01/
      data y_data(    72,   1) /   0.148328901313D+04/
      data y_data(    72,   2) /   0.134742077202D+03/
      data y_data(    72,   3) /   0.226611065662D-03/
      data y_data(    72,   4) /   0.903088732782D-01/
      data y_data(    72,   5) /   0.116460610749D+00/
      data y_data(    72,   6) /   0.219711322505D-01/
      data y_data(    72,   7) /   0.847678489289D-02/
      data y_data(    72,   8) /   0.397689403835D-01/
      data y_data(    72,   9) /   0.723013658446D+00/
      data x_data(    73     ) /   0.302905394300D+01/
      data y_data(    73,   1) /   0.149520775224D+04/
      data y_data(    73,   2) /   0.135814870718D+03/
      data y_data(    73,   3) /   0.224821078450D-03/
      data y_data(    73,   4) /   0.891348622920D-01/
      data y_data(    73,   5) /   0.117460557458D+00/
      data y_data(    73,   6) /   0.214133042231D-01/
      data y_data(    73,   7) /   0.851672473832D-02/
      data y_data(    73,   8) /   0.403947514817D-01/
      data y_data(    73,   9) /   0.723079799807D+00/
      data x_data(    74     ) /   0.302937471858D+01/
      data y_data(    74,   1) /   0.150706226615D+04/
      data y_data(    74,   2) /   0.136881131088D+03/
      data y_data(    74,   3) /   0.223069793928D-03/
      data y_data(    74,   4) /   0.879663160193D-01/
      data y_data(    74,   5) /   0.118451906934D+00/
      data y_data(    74,   6) /   0.208593815673D-01/
      data y_data(    74,   7) /   0.855175703366D-02/
      data y_data(    74,   8) /   0.410235941740D-01/
      data y_data(    74,   9) /   0.723147044272D+00/
      data x_data(    75     ) /   0.302969549416D+01/
      data y_data(    75,   1) /   0.151884478094D+04/
      data y_data(    75,   2) /   0.137940145402D+03/
      data y_data(    75,   3) /   0.221357209791D-03/
      data y_data(    75,   4) /   0.868040768352D-01/
      data y_data(    75,   5) /   0.119433996930D+00/
      data y_data(    75,   6) /   0.203097771314D-01/
      data y_data(    75,   7) /   0.858171899482D-02/
      data y_data(    75,   8) /   0.416550998478D-01/
      data y_data(    75,   9) /   0.723215330261D+00/
      data x_data(    76     ) /   0.303001626974D+01/
      data y_data(    76,   1) /   0.153054745748D+04/
      data y_data(    76,   2) /   0.138991197288D+03/
      data y_data(    76,   3) /   0.219683305850D-03/
      data y_data(    76,   4) /   0.856489930295D-01/
      data y_data(    76,   5) /   0.120406169504D+00/
      data y_data(    76,   6) /   0.197649024692D-01/
      data y_data(    76,   7) /   0.860646654141D-02/
      data y_data(    76,   8) /   0.422888761615D-01/
      data y_data(    76,   9) /   0.723284592294D+00/
      data x_data(    77     ) /   0.303033704532D+01/
      data y_data(    77,   1) /   0.154216242343D+04/
      data y_data(    77,   2) /   0.140033569997D+03/
      data y_data(    77,   3) /   0.218048041658D-03/
      data y_data(    77,   4) /   0.845019151905D-01/
      data y_data(    77,   5) /   0.121367774304D+00/
      data y_data(    77,   6) /   0.192251658058D-01/
      data y_data(    77,   7) /   0.862587613694D-02/
      data y_data(    77,   8) /   0.429245075094D-01/
      data y_data(    77,   9) /   0.723354761054D+00/
      data x_data(    78     ) /   0.303065782090D+01/
      data y_data(    78,   1) /   0.155368180660D+04/
      data y_data(    78,   2) /   0.141066549591D+03/
      data y_data(    78,   3) /   0.216451354293D-03/
      data y_data(    78,   4) /   0.833636924586D-01/
      data y_data(    78,   5) /   0.122318171878D+00/
      data y_data(    78,   6) /   0.186909699791D-01/
      data y_data(    78,   7) /   0.863984645996D-02/
      data y_data(    78,   8) /   0.435615557397D-01/
      data y_data(    78,   9) /   0.723425763485D+00/
      data x_data(    79     ) /   0.303097859648D+01/
      data y_data(    79,   1) /   0.156509776943D+04/
      data y_data(    79,   2) /   0.142089428211D+03/
      data y_data(    79,   3) /   0.214893156294D-03/
      data y_data(    79,   4) /   0.822351686913D-01/
      data y_data(    79,   5) /   0.123256736976D+00/
      data y_data(    79,   6) /   0.181627103809D-01/
      data y_data(    79,   7) /   0.864829987344D-02/
      data y_data(    79,   8) /   0.441995611316D-01/
      data y_data(    79,   9) /   0.723497522946D+00/
      data x_data(    80     ) /   0.303129937206D+01/
      data y_data(    80,   1) /   0.157640254423D+04/
      data y_data(    80,   2) /   0.143101507394D+03/
      data y_data(    80,   3) /   0.213373333799D-03/
      data y_data(    80,   4) /   0.811171785760D-01/
      data y_data(    80,   5) /   0.124182861802D+00/
      data y_data(    80,   6) /   0.176407729237D-01/
      data y_data(    80,   7) /   0.865118366226D-02/
      data y_data(    80,   8) /   0.448380436358D-01/
      data y_data(    80,   9) /   0.723569959400D+00/
      data x_data(    81     ) /   0.303162014764D+01/
      data y_data(    81,   1) /   0.158758846881D+04/
      data y_data(    81,   2) /   0.144102101382D+03/
      data y_data(    81,   3) /   0.211891744891D-03/
      data y_data(    81,   4) /   0.800105437357D-01/
      data y_data(    81,   5) /   0.125095959166D+00/
      data y_data(    81,   6) /   0.171255320563D-01/
      data y_data(    81,   7) /   0.864847101262D-02/
      data y_data(    81,   8) /   0.454765043789D-01/
      data y_data(    81,   9) /   0.723642989650D+00/
      data x_data(    82     ) /   0.303194092322D+01/
      data y_data(    82,   1) /   0.159864802212D+04/
      data y_data(    82,   2) /   0.145090540415D+03/
      data y_data(    82,   3) /   0.210448218174D-03/
      data y_data(    82,   4) /   0.789160688685D-01/
      data y_data(    82,   5) /   0.125995465520D+00/
      data y_data(    82,   6) /   0.166173488538D-01/
      data y_data(    82,   7) /   0.864016171155D-02/
      data y_data(    82,   8) /   0.461144274255D-01/
      data y_data(    82,   9) /   0.723716527621D+00/
      data x_data(    83     ) /   0.303226169880D+01/
      data y_data(    83,   1) /   0.160957385945D+04/
      data y_data(    83,   2) /   0.146066173950D+03/
      data y_data(    83,   3) /   0.209042551595D-03/
      data y_data(    83,   4) /   0.778345379633D-01/
      data y_data(    83,   5) /   0.126880843814D+00/
      data y_data(    83,   6) /   0.161165692043D-01/
      data y_data(    83,   7) /   0.862628255004D-02/
      data y_data(    83,   8) /   0.467512817866D-01/
      data y_data(    83,   9) /   0.723790484682D+00/
      data x_data(    84     ) /   0.303258247438D+01/
      data y_data(    84,   1) /   0.162035884701D+04/
      data y_data(    84,   2) /   0.147028373777D+03/
      data y_data(    84,   3) /   0.207674511525D-03/
      data y_data(    84,   4) /   0.767667106354D-01/
      data y_data(    84,   5) /   0.127751586165D+00/
      data y_data(    84,   6) /   0.156235221148D-01/
      data y_data(    84,   7) /   0.860688741894D-02/
      data y_data(    84,   8) /   0.473865236607D-01/
      data y_data(    84,   9) /   0.723864770005D+00/
      data x_data(    85     ) /   0.303290324996D+01/
      data y_data(    85,   1) /   0.163099609525D+04/
      data y_data(    85,   2) /   0.147976536992D+03/
      data y_data(    85,   3) /   0.206343832103D-03/
      data y_data(    85,   4) /   0.757133186198D-01/
      data y_data(    85,   5) /   0.128607216283D+00/
      data y_data(    85,   6) /   0.151385181552D-01/
      data y_data(    85,   7) /   0.858205709278D-02/
      data y_data(    85,   8) /   0.480195988850D-01/
      data y_data(    85,   9) /   0.723939290965D+00/
      data x_data(    86     ) /   0.303322402554D+01/
      data y_data(    86,   1) /   0.164147899072D+04/
      data y_data(    86,   2) /   0.148910088809D+03/
      data y_data(    86,   3) /   0.205050214854D-03/
      data y_data(    86,   4) /   0.746750624625D-01/
      data y_data(    86,   5) /   0.129447291645D+00/
      data y_data(    86,   6) /   0.146618480579D-01/
      data y_data(    86,   7) /   0.855189870314D-02/
      data y_data(    86,   8) /   0.486499455715D-01/
      data y_data(    86,   9) /   0.724013953560D+00/
      data x_data(    87     ) /   0.303354480112D+01/
      data y_data(    87,   1) /   0.165180122610D+04/
      data y_data(    87,   2) /   0.149828485157D+03/
      data y_data(    87,   3) /   0.203793328567D-03/
      data y_data(    87,   4) /   0.736526084426D-01/
      data y_data(    87,   5) /   0.130271405389D+00/
      data y_data(    87,   6) /   0.141937814874D-01/
      data y_data(    87,   7) /   0.851654490923D-02/
      data y_data(    87,   8) /   0.492769969003D-01/
      data y_data(    87,   9) /   0.724088662871D+00/
      data x_data(    88     ) /   0.303386557670D+01/
      data y_data(    88,   1) /   0.166195682809D+04/
      data y_data(    88,   2) /   0.150731215052D+03/
      data y_data(    88,   3) /   0.202572809446D-03/
      data y_data(    88,   4) /   0.726465857577D-01/
      data y_data(    88,   5) /   0.131079187906D+00/
      data y_data(    88,   6) /   0.137345659919D-01/
      data y_data(    88,   7) /   0.847615277942D-02/
      data y_data(    88,   8) /   0.499001840348D-01/
      data y_data(    88,   9) /   0.724163323530D+00/
      data x_data(    89     ) /   0.303418635228D+01/
      data y_data(    89,   1) /   0.167194018279D+04/
      data y_data(    89,   2) /   0.151617802717D+03/
      data y_data(    89,   3) /   0.201388261517D-03/
      data y_data(    89,   4) /   0.716575839987D-01/
      data y_data(    89,   5) /   0.131870308125D+00/
      data y_data(    89,   6) /   0.132844261439D-01/
      data y_data(    89,   7) /   0.843090240317D-02/
      data y_data(    89,   8) /   0.505189391240D-01/
      data y_data(    89,   9) /   0.724237840205D+00/
      data x_data(    90     ) /   0.303450712786D+01/
      data y_data(    90,   1) /   0.168174605843D+04/
      data y_data(    90,   2) /   0.152487809426D+03/
      data y_data(    90,   3) /   0.200239257284D-03/
      data y_data(    90,   4) /   0.706861509367D-01/
      data y_data(    90,   5) /   0.132644474476D+00/
      data y_data(    90,   6) /   0.128435628773D-01/
      data y_data(    90,   7) /   0.838099525776D-02/
      data y_data(    90,   8) /   0.511326983533D-01/
      data y_data(    90,   9) /   0.724312118100D+00/
      data x_data(    91     ) /   0.303482790344D+01/
      data y_data(    91,   1) /   0.169136962526D+04/
      data y_data(    91,   2) /   0.153340835056D+03/
      data y_data(    91,   3) /   0.199125338617D-03/
      data y_data(    91,   4) /   0.697327906399D-01/
      data y_data(    91,   5) /   0.133401435538D+00/
      data y_data(    91,   6) /   0.124121530199D-01/
      data y_data(    91,   7) /   0.832665235874D-02/
      data y_data(    91,   8) /   0.517409050048D-01/
      data y_data(    91,   9) /   0.724386063439D+00/
      data x_data(    92     ) /   0.303514867902D+01/
      data y_data(    92,   1) /   0.170080647227D+04/
      data y_data(    92,   2) /   0.154176519348D+03/
      data y_data(    92,   3) /   0.198046017860D-03/
      data y_data(    92,   4) /   0.687979619313D-01/
      data y_data(    92,   5) /   0.134140980367D+00/
      data y_data(    92,   6) /   0.119903490236D-01/
      data y_data(    92,   7) /   0.826811222650D-02/
      data y_data(    92,   8) /   0.523430124873D-01/
      data y_data(    92,   9) /   0.724459583964D+00/
      data x_data(    93     ) /   0.303579023017D+01/
      data y_data(    93,   1) /   0.171911072273D+04/
      data y_data(    93,   2) /   0.155795150237D+03/
      data y_data(    93,   3) /   0.195988422347D-03/
      data y_data(    93,   4) /   0.669849207971D-01/
      data y_data(    93,   5) /   0.135567501410D+00/
      data y_data(    93,   6) /   0.111758471130D-01/
      data y_data(    93,   7) /   0.813921497843D-02/
      data y_data(    93,   8) /   0.535274311502D-01/
      data y_data(    93,   9) /   0.724605084551D+00/
      data x_data(    94     ) /   0.303643178133D+01/
      data y_data(    94,   1) /   0.173663018023D+04/
      data y_data(    94,   2) /   0.157341480103D+03/
      data y_data(    94,   3) /   0.194062275786D-03/
      data y_data(    94,   4) /   0.652499094922D-01/
      data y_data(    94,   5) /   0.136923114714D+00/
      data y_data(    94,   6) /   0.104007960943D-01/
      data y_data(    94,   7) /   0.799680342802D-02/
      data y_data(    94,   8) /   0.546814942774D-01/
      data y_data(    94,   9) /   0.724747881994D+00/
      data x_data(    95     ) /   0.303707333249D+01/
      data y_data(    95,   1) /   0.175334571848D+04/
      data y_data(    95,   2) /   0.158814127225D+03/
      data y_data(    95,   3) /   0.192262780635D-03/
      data y_data(    95,   4) /   0.635948775867D-01/
      data y_data(    95,   5) /   0.138207556890D+00/
      data y_data(    95,   6) /   0.966554847735D-02/
      data y_data(    95,   7) /   0.784317475609D-02/
      data y_data(    95,   8) /   0.558015045028D-01/
      data y_data(    95,   9) /   0.724887337787D+00/
      data x_data(    96     ) /   0.303771488365D+01/
      data y_data(    96,   1) /   0.176924540671D+04/
      data y_data(    96,   2) /   0.160212363519D+03/
      data y_data(    96,   3) /   0.190584827747D-03/
      data y_data(    96,   4) /   0.620210226180D-01/
      data y_data(    96,   5) /   0.139421146497D+00/
      data y_data(    96,   6) /   0.897010143951D-02/
      data y_data(    96,   7) /   0.768068368012D-02/
      data y_data(    96,   8) /   0.568841695438D-01/
      data y_data(    96,   9) /   0.725022876222D+00/
      data x_data(    97     ) /   0.303835643481D+01/
      data y_data(    97,   1) /   0.178432430625D+04/
      data y_data(    97,   2) /   0.161536086746D+03/
      data y_data(    97,   3) /   0.189023061777D-03/
      data y_data(    97,   4) /   0.605288185814D-01/
      data y_data(    97,   5) /   0.140564735090D+00/
      data y_data(    97,   6) /   0.831412521995D-02/
      data y_data(    97,   7) /   0.751167117935D-02/
      data y_data(    97,   8) /   0.579266568241D-01/
      data y_data(    97,   9) /   0.725153993105D+00/
      data x_data(    98     ) /   0.303899798597D+01/
      data y_data(    98,   1) /   0.179858410579D+04/
      data y_data(    98,   2) /   0.162785779063D+03/
      data y_data(    98,   3) /   0.187571948116D-03/
      data y_data(    98,   4) /   0.591180602210D-01/
      data y_data(    98,   5) /   0.141639649369D+00/
      data y_data(    98,   6) /   0.769699716297D-02/
      data y_data(    98,   7) /   0.733840069863D-02/
      data y_data(    98,   8) /   0.589266308657D-01/
      data y_data(    98,   9) /   0.725280261682D+00/
      data x_data(    99     ) /   0.303963953713D+01/
      data y_data(    99,   1) /   0.181203262426D+04/
      data y_data(    99,   2) /   0.163962454874D+03/
      data y_data(    99,   3) /   0.186225838883D-03/
      data y_data(    99,   4) /   0.577879198441D-01/
      data y_data(    99,   5) /   0.142647627735D+00/
      data y_data(    99,   6) /   0.711783936940D-02/
      data y_data(    99,   7) /   0.716300431401D-02/
      data y_data(    99,   8) /   0.598822730029D-01/
      data y_data(    99,   9) /   0.725401335735D+00/
      data x_data(   100     ) /   0.304028108829D+01/
      data y_data(   100,   1) /   0.182468321279D+04/
      data y_data(   100,   2) /   0.165067601074D+03/
      data y_data(   100,   3) /   0.184979035896D-03/
      data y_data(   100,   4) /   0.565370132112D-01/
      data y_data(   100,   5) /   0.143590754353D+00/
      data y_data(   100,   6) /   0.657555805260D-02/
      data y_data(   100,   7) /   0.698744032878D-02/
      data y_data(   100,   8) /   0.607922840766D-01/
      data y_data(   100,   9) /   0.725516949977D+00/
      data x_data(   101     ) /   0.304092263945D+01/
      data y_data(   101,   1) /   0.183655408830D+04/
      data y_data(   101,   2) /   0.166103112682D+03/
      data y_data(   101,   3) /   0.183825848963D-03/
      data y_data(   101,   4) /   0.553634711182D-01/
      data y_data(   101,   5) /   0.144471393431D+00/
      data y_data(   101,   6) /   0.606888293347D-02/
      data y_data(   101,   7) /   0.681346280137D-02/
      data y_data(   101,   8) /   0.616558716818D-01/
      data y_data(   101,   9) /   0.725626918035D+00/
      data x_data(   102     ) /   0.304156419061D+01/
      data y_data(   102,   1) /   0.184766762937D+04/
      data y_data(   102,   2) /   0.167071226682D+03/
      data y_data(   102,   3) /   0.182760648322D-03/
      data y_data(   102,   4) /   0.542650135395D-01/
      data y_data(   102,   5) /   0.145292125893D+00/
      data y_data(   102,   6) /   0.559640530555D-02/
      data y_data(   102,   7) /   0.664260267059D-02/
      data y_data(   102,   8) /   0.624727242141D-01/
      data y_data(   102,   9) /   0.725731128378D+00/
      data x_data(   103     ) /   0.304220574177D+01/
      data y_data(   103,   1) /   0.185804966248D+04/
      data y_data(   103,   2) /   0.167974456435D+03/
      data y_data(   103,   3) /   0.181777910477D-03/
      data y_data(   103,   4) /   0.532390235908D-01/
      data y_data(   103,   5) /   0.146055690183D+00/
      data y_data(   103,   6) /   0.515661372117D-02/
      data y_data(   103,   7) /   0.647615949243D-02/
      data y_data(   103,   8) /   0.632429743659D-01/
      data y_data(   103,   9) /   0.725829538647D+00/
      data x_data(   104     ) /   0.304284729293D+01/
      data y_data(   104,   1) /   0.186772876237D+04/
      data y_data(   104,   2) /   0.168815528689D+03/
      data y_data(   104,   3) /   0.180872257081D-03/
      data y_data(   104,   4) /   0.522826190378D-01/
      data y_data(   104,   5) /   0.146764928343D+00/
      data y_data(   104,   6) /   0.474792656243D-02/
      data y_data(   104,   7) /   0.631520235523D-02/
      data y_data(   104,   8) /   0.639671548849D-01/
      data y_data(   104,   9) /   0.725922168816D+00/
      data x_data(   105     ) /   0.304316806851D+01/
      data y_data(   105,   1) /   0.187231568258D+04/
      data y_data(   105,   2) /   0.169213785691D+03/
      data y_data(   105,   3) /   0.180446561015D-03/
      data y_data(   105,   4) /   0.518293974006D-01/
      data y_data(   105,   5) /   0.147100229251D+00/
      data y_data(   105,   6) /   0.455465506837D-02/
      data y_data(   105,   7) /   0.623710395355D-02/
      data y_data(   105,   8) /   0.643122739098D-01/
      data y_data(   105,   9) /   0.725966340417D+00/
      data x_data(   106     ) /   0.304348884409D+01/
      data y_data(   106,   1) /   0.187673762696D+04/
      data y_data(   106,   2) /   0.169597519301D+03/
      data y_data(   106,   3) /   0.180038280218D-03/
      data y_data(   106,   4) /   0.513924965100D-01/
      data y_data(   106,   5) /   0.147422984837D+00/
      data y_data(   106,   6) /   0.436858648808D-02/
      data y_data(   106,   7) /   0.616068511135D-02/
      data y_data(   106,   8) /   0.646461543400D-01/
      data y_data(   106,   9) /   0.726009092714D+00/
      data x_data(   107     ) /   0.304413039524D+01/
      data y_data(   107,   1) /   0.188509971071D+04/
      data y_data(   107,   2) /   0.170322634892D+03/
      data y_data(   107,   3) /   0.179271802152D-03/
      data y_data(   107,   4) /   0.505663637868D-01/
      data y_data(   107,   5) /   0.148032012546D+00/
      data y_data(   107,   6) /   0.401741177394D-02/
      data y_data(   107,   7) /   0.601309992511D-02/
      data y_data(   107,   8) /   0.652807149784D-01/
      data y_data(   107,   9) /   0.726090396990D+00/
      data x_data(   108     ) /   0.304477194641D+01/
      data y_data(   108,   1) /   0.189285457073D+04/
      data y_data(   108,   2) /   0.170994484225D+03/
      data y_data(   108,   3) /   0.178567430655D-03/
      data y_data(   108,   4) /   0.498002324962D-01/
      data y_data(   108,   5) /   0.148595411399D+00/
      data y_data(   108,   6) /   0.369244992279D-02/
      data y_data(   108,   7) /   0.587294056849D-02/
      data y_data(   108,   8) /   0.658726876114D-01/
      data y_data(   108,   9) /   0.726166278002D+00/
      data x_data(   109     ) /   0.304541349756D+01/
      data y_data(   109,   1) /   0.190003560816D+04/
      data y_data(   109,   2) /   0.171616110561D+03/
      data y_data(   109,   3) /   0.177920625310D-03/
      data y_data(   109,   4) /   0.490907761448D-01/
      data y_data(   109,   5) /   0.149116019609D+00/
      data y_data(   109,   6) /   0.339209241168D-02/
      data y_data(   109,   7) /   0.574048747563D-02/
      data y_data(   109,   8) /   0.664236968284D-01/
      data y_data(   109,   9) /   0.726236927530D+00/
      data x_data(   110     ) /   0.304605504872D+01/
      data y_data(   110,   1) /   0.190667619646D+04/
      data y_data(   110,   2) /   0.172190532303D+03/
      data y_data(   110,   3) /   0.177327088174D-03/
      data y_data(   110,   4) /   0.484346783746D-01/
      data y_data(   110,   5) /   0.149596601364D+00/
      data y_data(   110,   6) /   0.311476859593D-02/
      data y_data(   110,   7) /   0.561587407090D-02/
      data y_data(   110,   8) /   0.669355161192D-01/
      data y_data(   110,   9) /   0.726302561475D+00/
      data x_data(   111     ) /   0.304669659988D+01/
      data y_data(   111,   1) /   0.191280931679D+04/
      data y_data(   111,   2) /   0.172720713389D+03/
      data y_data(   111,   3) /   0.176782767423D-03/
      data y_data(   111,   4) /   0.478286681242D-01/
      data y_data(   111,   5) /   0.150039828501D+00/
      data y_data(   111,   6) /   0.285895701671D-02/
      data y_data(   111,   7) /   0.549910873740D-02/
      data y_data(   111,   8) /   0.674100243054D-01/
      data y_data(   111,   9) /   0.726363413315D+00/
      data x_data(   112     ) /   0.304733815104D+01/
      data y_data(   112,   1) /   0.191846725645D+04/
      data y_data(   112,   2) /   0.173209539288D+03/
      data y_data(   112,   3) /   0.176283857286D-03/
      data y_data(   112,   4) /   0.472695484635D-01/
      data y_data(   112,   5) /   0.150448266767D+00/
      data y_data(   112,   6) /   0.262319396318D-02/
      data y_data(   112,   7) /   0.539009605323D-02/
      data y_data(   112,   8) /   0.678491664998D-01/
      data y_data(   112,   9) /   0.726419728253D+00/
      data x_data(   113     ) /   0.304797970220D+01/
      data y_data(   113,   1) /   0.192368136619D+04/
      data y_data(   113,   2) /   0.173659798120D+03/
      data y_data(   113,   3) /   0.175826794888D-03/
      data y_data(   113,   4) /   0.467542195940D-01/
      data y_data(   113,   5) /   0.150824366051D+00/
      data y_data(   113,   6) /   0.240607964461D-02/
      data y_data(   113,   7) /   0.528865669703D-02/
      data y_data(   113,   8) /   0.682549199032D-01/
      data y_data(   113,   9) /   0.726471758110D+00/
      data x_data(   114     ) /   0.304862125336D+01/
      data y_data(   114,   1) /   0.192848187118D+04/
      data y_data(   114,   2) /   0.174074166384D+03/
      data y_data(   114,   3) /   0.175408254645D-03/
      data y_data(   114,   4) /   0.462796965830D-01/
      data y_data(   114,   5) /   0.151170454022D+00/
      data y_data(   114,   6) /   0.220628232074D-02/
      data y_data(   114,   7) /   0.519454562892D-02/
      data y_data(   114,   8) /   0.686292644916D-01/
      data y_data(   114,   9) /   0.726519756954D+00/
      data x_data(   115     ) /   0.304990435568D+01/
      data y_data(   115,   1) /   0.193693114937D+04/
      data y_data(   115,   2) /   0.174803109714D+03/
      data y_data(   115,   3) /   0.174676787812D-03/
      data y_data(   115,   4) /   0.454443259272D-01/
      data y_data(   115,   5) /   0.151779332721D+00/
      data y_data(   115,   6) /   0.185478847728D-02/
      data y_data(   115,   7) /   0.502739339012D-02/
      data y_data(   115,   8) /   0.692897196108D-01/
      data y_data(   115,   9) /   0.726604439874D+00/
      data x_data(   116     ) /   0.305118745800D+01/
      data y_data(   116,   1) /   0.194407001750D+04/
      data y_data(   116,   2) /   0.175418671491D+03/
      data y_data(   116,   3) /   0.174063829380D-03/
      data y_data(   116,   4) /   0.447381804981D-01/
      data y_data(   116,   5) /   0.152293777110D+00/
      data y_data(   116,   6) /   0.155776551027D-02/
      data y_data(   116,   7) /   0.488534753762D-02/
      data y_data(   116,   8) /   0.698488774458D-01/
      data y_data(   116,   9) /   0.726676051899D+00/
      data x_data(   117     ) /   0.305247056032D+01/
      data y_data(   117,   1) /   0.195008829978D+04/
      data y_data(   117,   2) /   0.175937432099D+03/
      data y_data(   117,   3) /   0.173550593186D-03/
      data y_data(   117,   4) /   0.441425823377D-01/
      data y_data(   117,   5) /   0.152727771049D+00/
      data y_data(   117,   6) /   0.130718838878D-02/
      data y_data(   117,   7) /   0.476546803553D-02/
      data y_data(   117,   8) /   0.703205929724D-01/
      data y_data(   117,   9) /   0.726736397217D+00/
      data x_data(   118     ) /   0.305375366263D+01/
      data y_data(   118,   1) /   0.195515319412D+04/
      data y_data(   118,   2) /   0.176373936257D+03/
      data y_data(   118,   3) /   0.173121076460D-03/
      data y_data(   118,   4) /   0.436410878093D-01/
      data y_data(   118,   5) /   0.153093479869D+00/
      data y_data(   118,   6) /   0.109606582002D-02/
      data y_data(   118,   7) /   0.466483376101D-02/
      data y_data(   118,   8) /   0.707174188512D-01/
      data y_data(   118,   9) /   0.726787113890D+00/
      data x_data(   119     ) /   0.305503676495D+01/
      data y_data(   119,   1) /   0.195941036888D+04/
      data y_data(   119,   2) /   0.176740815877D+03/
      data y_data(   119,   3) /   0.172761710717D-03/
      data y_data(   119,   4) /   0.432193717325D-01/
      data y_data(   119,   5) /   0.153401408011D+00/
      data y_data(   119,   6) /   0.918353555094D-03/
      data y_data(   119,   7) /   0.458069002931D-02/
      data y_data(   119,   8) /   0.710505176048D-01/
      data y_data(   119,   9) /   0.726829659067D+00/
      data x_data(   120     ) /   0.305631986727D+01/
      data y_data(   120,   1) /   0.196298566476D+04/
      data y_data(   120,   2) /   0.177048957064D+03/
      data y_data(   120,   3) /   0.172461031179D-03/
      data y_data(   120,   4) /   0.428650556915D-01/
      data y_data(   120,   5) /   0.153660573809D+00/
      data y_data(   120,   6) /   0.768856679489D-03/
      data y_data(   120,   7) /   0.451052951520D-02/
      data y_data(   120,   8) /   0.713296752227D-01/
      data y_data(   120,   9) /   0.726865309083D+00/
      data x_data(   121     ) /   0.305888607191D+01/
      data y_data(   121,   1) /   0.196841685534D+04/
      data y_data(   121,   2) /   0.177517218303D+03/
      data y_data(   121,   3) /   0.172006107330D-03/
      data y_data(   121,   4) /   0.423265625949D-01/
      data y_data(   121,   5) /   0.154055875513D+00/
      data y_data(   121,   6) /   0.541107383644D-03/
      data y_data(   121,   7) /   0.440544789547D-02/
      data y_data(   121,   8) /   0.717517471205D-01/
      data y_data(   121,   9) /   0.726919259493D+00/
      data x_data(   122     ) /   0.306145227655D+01/
      data y_data(   122,   1) /   0.197225423109D+04/
      data y_data(   122,   2) /   0.177848204866D+03/
      data y_data(   122,   3) /   0.171685993274D-03/
      data y_data(   122,   4) /   0.419458134954D-01/
      data y_data(   122,   5) /   0.154336447762D+00/
      data y_data(   122,   6) /   0.379618505213D-03/
      data y_data(   122,   7) /   0.433262900862D-02/
      data y_data(   122,   8) /   0.720483647761D-01/
      data y_data(   122,   9) /   0.726957126452D+00/
      data x_data(   123     ) /   0.306401848118D+01/
      data y_data(   123,   1) /   0.197497254587D+04/
      data y_data(   123,   2) /   0.178082809572D+03/
      data y_data(   123,   3) /   0.171459815676D-03/
      data y_data(   123,   4) /   0.416759937334D-01/
      data y_data(   123,   5) /   0.154536208626D+00/
      data y_data(   123,   6) /   0.264837137496D-03/
      data y_data(   123,   7) /   0.428201658373D-02/
      data y_data(   123,   8) /   0.722571450615D-01/
      data y_data(   123,   9) /   0.726983798858D+00/
      data x_data(   124     ) /   0.306915089046D+01/
      data y_data(   124,   1) /   0.197807929242D+04/
      data y_data(   124,   2) /   0.178351309804D+03/
      data y_data(   124,   3) /   0.171201690292D-03/
      data y_data(   124,   4) /   0.413676831255D-01/
      data y_data(   124,   5) /   0.154766741734D+00/
      data y_data(   124,   6) /   0.132986848933D-03/
      data y_data(   124,   7) /   0.422583234277D-02/
      data y_data(   124,   8) /   0.724926834827D-01/
      data y_data(   124,   9) /   0.727014072466D+00/
      data x_data(   125     ) /   0.307428329973D+01/
      data y_data(   125,   1) /   0.197969012487D+04/
      data y_data(   125,   2) /   0.178490709869D+03/
      data y_data(   125,   3) /   0.171067982903D-03/
      data y_data(   125,   4) /   0.412078966022D-01/
      data y_data(   125,   5) /   0.154887378259D+00/
      data y_data(   125,   6) /   0.643252430993D-04/
      data y_data(   125,   7) /   0.419741683500D-02/
      data y_data(   125,   8) /   0.726133344081D-01/
      data y_data(   125,   9) /   0.727029648653D+00/
      data x_data(   126     ) /   0.308454811828D+01/
      data y_data(   126,   1) /   0.198080388572D+04/
      data y_data(   126,   2) /   0.178587382085D+03/
      data y_data(   126,   3) /   0.170975381059D-03/
      data y_data(   126,   4) /   0.410977952248D-01/
      data y_data(   126,   5) /   0.154972410777D+00/
      data y_data(   126,   6) /   0.166105680787D-04/
      data y_data(   126,   7) /   0.417818077711D-02/
      data y_data(   126,   8) /   0.726946379211D-01/
      data y_data(   126,   9) /   0.727040364732D+00/
      data x_data(   127     ) /   0.310507775538D+01/
      data y_data(   127,   1) /   0.198114059349D+04/
      data y_data(   127,   2) /   0.178616675601D+03/
      data y_data(   127,   3) /   0.170947340731D-03/
      data y_data(   127,   4) /   0.410646189965D-01/
      data y_data(   127,   5) /   0.154998521188D+00/
      data y_data(   127,   6) /   0.214374119692D-05/
      data y_data(   127,   7) /   0.417240775895D-02/
      data y_data(   127,   8) /   0.727187423268D-01/
      data y_data(   127,   9) /   0.727043565989D+00/
      data x_data(   128     ) /   0.312560739247D+01/
      data y_data(   128,   1) /   0.198118488736D+04/
      data y_data(   128,   2) /   0.178620539275D+03/
      data y_data(   128,   3) /   0.170943643034D-03/
      data y_data(   128,   4) /   0.410602746616D-01/
      data y_data(   128,   5) /   0.155002017876D+00/
      data y_data(   128,   6) /   0.237385198974D-06/
      data y_data(   128,   7) /   0.417164433993D-02/
      data y_data(   128,   8) /   0.727218458894D-01/
      data y_data(   128,   9) /   0.727043979848D+00/
      data x_data(   129     ) /   0.316666666667D+01/
      data y_data(   129,   1) /   0.198119014284D+04/
      data y_data(   129,   2) /   0.178620999929D+03/
      data y_data(   129,   3) /   0.170943202179D-03/
      data y_data(   129,   4) /   0.410597639004D-01/
      data y_data(   129,   5) /   0.155002447192D+00/
      data y_data(   129,   6) /   0.107279019713D-07/
      data y_data(   129,   7) /   0.417155198334D-02/
      data y_data(   129,   8) /   0.727221999526D-01/
      data y_data(   129,   9) /   0.727044026244D+00/
      data x_data(   130     ) /   0.325000000000D+01/
      data y_data(   130,   1) /   0.198119038651D+04/
      data y_data(   130,   2) /   0.178621021323D+03/
      data y_data(   130,   3) /   0.170943181705D-03/
      data y_data(   130,   4) /   0.410597403102D-01/
      data y_data(   130,   5) /   0.155002467346D+00/
      data y_data(   130,   6) /   0.224306769354D-09/
      data y_data(   130,   7) /   0.417154762819D-02/
      data y_data(   130,   8) /   0.727222161556D-01/
      data y_data(   130,   9) /   0.727044028336D+00/
      data x_data(   131     ) /   0.333333333333D+01/
      data y_data(   131,   1) /   0.198119039161D+04/
      data y_data(   131,   2) /   0.178621021772D+03/
      data y_data(   131,   3) /   0.170943181275D-03/
      data y_data(   131,   4) /   0.410597398182D-01/
      data y_data(   131,   5) /   0.155002467774D+00/
      data y_data(   131,   6) /   0.428945840687D-11/
      data y_data(   131,   7) /   0.417154753568D-02/
      data y_data(   131,   8) /   0.727222164899D-01/
      data y_data(   131,   9) /   0.727044028378D+00/
      data x_data(   132     ) /   0.350000000000D+01/
      data y_data(   132,   1) /   0.198119039161D+04/
      data y_data(   132,   2) /   0.178621021772D+03/
      data y_data(   132,   3) /   0.170943181275D-03/
      data y_data(   132,   4) /   0.410597398182D-01/
      data y_data(   132,   5) /   0.155002467774D+00/
      data y_data(   132,   6) /   0.428945840687D-11/
      data y_data(   132,   7) /   0.417154753568D-02/
      data y_data(   132,   8) /   0.727222164899D-01/
      data y_data(   132,   9) /   0.727044028378D+00/
c                                                 
c     interpolation routine                       
c                                                 
      lo_loside = 0
      lo_hiside = 0
      hi_loside = 0
      hi_hiside = 0
      if (xlo .le. x_data(1)) then
         lo_loside = 1
         lo_hiside = 1
      end if
      if (xhi .le. x_data(1)) then
         hi_loside = 1
         hi_hiside = 1
      end if
      if (xlo .ge. x_data(N)) then
         lo_loside = N
         lo_hiside = N
      end if
      if (xhi .ge. x_data(N)) then
         hi_loside = N
         hi_hiside = N
      end if
      if (lo_loside.eq.0) then
         do i = 1, N-1                           
            if ( (xlo .ge. x_data(i))
     &           .and.
     &           (xlo .le. x_data(i+1)) ) then
               lo_loside  = i
               lo_hiside  = i+1
            end if
         end do
      end if
      if (hi_loside.eq.0) then            
         do i = 1, N-1                           
            if ( (xhi .ge. x_data(i))
     &           .and.
     &           (xhi .le. x_data(i+1)) ) then
               hi_loside = i
               hi_hiside = i + 1
            end if
         end do
      end if
         
      do j = 1, M
         
         x1 = x_data(lo_loside)
         y1 = y_data(lo_loside,j)
         
         x2 = x_data(lo_hiside)
         y2 = y_data(lo_hiside,j)
          
         if (lo_loside.eq.lo_hiside) then
            dydx = 0.d0
         else
            dydx = (y2-y1)/(x2-x1)
         end if
         
         ylo = y1 + dydx*(xlo - x1)
         
         if (lo_loside .eq. hi_loside) then
            
            yhi = y1 + dydx*(xhi - x1)
            
            y_vector(j) = 0.5d0*(ylo + yhi)
            
         else
            
            sum = (x2 - xlo) * 0.5d0 * (ylo + y2)
            
            x1 = x_data(hi_loside)
            y1 = y_data(hi_loside,j)
         
            x2 = x_data(hi_hiside)
            y2 = y_data(hi_hiside,j)
            
            if (hi_loside.eq.hi_hiside) then
               dydx = 0.d0
            else
               dydx = (y2-y1)/(x2-x1)
            end if
            
            yhi = y1 + dydx*(xhi - x1)
            
            sum = sum + (xhi - x1)*0.5d0*(yhi+y1)
            
            do k = lo_hiside,hi_loside-1
               
               sum = sum + (x_data(k+1)-x_data(k))
     &              * 0.5d0
     &              * (y_data(k,j) + y_data(k+1,j))
               
            end do
            
            y_vector(j) = sum / (xhi - xlo)
            
         end if
      end do
      end                                         
c     LAST LINE                                   
c-------------------------------------------------
