[tool.poetry]
name = "ceptr"
version = "0.1.0"
description = ""
authors = ["Marc Henry de Frahan <marc.henrydefrahan@nrel.gov>", "Lucas Esclapez", "Jon Rood", "Hari Sitaraman", "Marc Day", "Anne Felden", "Julia Ream", "Malik Hassanaly", "Nick Wimer"]

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
Cantera = ">=3.2.0"
Pint = "^0.24"
PyYAML = "^6.0.1"
networkx = "^2.8.8"
matplotlib = "^3.10.0"
scipy = "^1.16.1"
numpy = "^2.3.0"
sympy = "==1.14"
symengine = "^0.14.0"
pandas = ">=2.3.3"
toml = ">=0.10.2"
pyarrow = ">=19.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.9.0"
ipython = "^8.14.0"
clang-format = "==20.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
convert = "ceptr.ceptr:main"
qssa = "ceptr.qssa:main"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "W", "B", "N", "D", "FLY", "C90", "I"]
ignore = [
    "E203",
    "E302",
    "E501",
    "C901",
    "D1",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["ceptr"]
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
]
