#ifndef PPHYS_CONSTANTS_H
#define PPHYS_CONSTANTS_H

#include <AMReX_REAL.H>

static constexpr amrex::Real PP_RU_CGS = 83144626.1815324;
static constexpr amrex::Real PP_RU_MKS = 8.31446261815324;
static constexpr amrex::Real PP_PA_CGS = 1013250.0;
static constexpr amrex::Real PP_PA_MKS = 101325.0;
static constexpr amrex::Real PP_RUC_CGS = 1.98721558317399615845;

static constexpr amrex::Real C_AW = 12.011150;
static constexpr amrex::Real H_AW = 1.007970;
static constexpr amrex::Real O_AW = 15.999400;
static constexpr amrex::Real N_AW = 14.006700;
static constexpr amrex::Real AR_AW = 39.948000;

#endif
