#!/bin/bash -l
#SBATCH -q debug
##SBATCH -N 9
#SBATCH -N 6
#SBATCH -t 00:30:00
#SBATCH -J ovf-test
#SBATCH -L SCRATCH
#SBATCH -C haswell

srun -n 1 ./Pele2d.gnu.haswell.MPI.ex inputs.2d  >& output.$SLURM_JOBID 
